### ISSUE TITLE
Getting 4905 Segmentation fault (core dumped) when running `icingacli director kickstart run`

### ISSUE THREAD

**Issue by briansumma** [Icinga/icingaweb2-module-director#1056]
## Context

When adding new scripts to `/etc/icinga2/scripts`, I typically run `systemctl restart icinga2` [to make sure Icinga sees them] then `icingacli director kickstart run` so that they appear in _Icinga Director > Commands_ as new external objects. Recently I started noticing that I will randomly get the error `4905 Segmentation fault (core dumped) when running icingacli director kickstart run`.

```
~]# abrt-cli list --since 1501770254
id 0f73a2cb6c85e9de67498fa2766cda7f9953f97b
reason:         php killed by SIGSEGV
time:           Wed 02 Aug 2017 12:38:38 PM EDT
cmdline:        /usr/bin/php /usr/bin/icingacli director kickstart run
package:        php-cli-5.4.16-42.el7
uid:            0 (root)
count:          3
Directory:      /var/spool/abrt/ccpp-2017-08-02-12:38:38-20837
```

## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): r2.7.0-1
* Operating System and version: CentOS Linux release 7.2.1511 (Core), kernel 3.10.0-327.el7.x86_64
* Webserver, PHP versions: Apache/2.4.6 (CentOS), PHP 5.4.16, Zend Engine v2.4.0,

**Comment by lazyfrosch** [comment]
This sounds likely to be the same issue mentioned here: https://github.com/Icinga/icingaweb2-module-director/issues/326#issuecomment-273104974

PHP 5.4.16 had a bug that can crash a program.

Crashes are nothing we can do about, since it means PHP either has an error, or doesn't handle an error  correctly.

In the other issue we internally disabled PHP's GC to avoid this on rendering config.

Seems like kickstart is affected by this too... :cry:

**Comment by lazyfrosch** [comment]
Poking @Thomas-Gelf on this as well

**Comment by briansumma** [comment]
I don't know if this is related or not, but I have also been noticing a `zend_mm_heap corrupted` error every once in a while as well.

Is there a preferred version of PHP is PHP 5.4.16 is known to be buggy?

**Comment by Thomas-Gelf** [comment]
@briansumma: PHP 5.4 is not only buggy but out of active support since two years and gets not security updates since a year. I'd strongly suggest to move to at least PHP 5.6 (might still have this bug), PHP 7.x should be preferred as it is much faster while using less memory. Still, we continue to support 5.4.

It's hard to avoid those issues. As @lazyfrosch already wrote, they happen at GC time. I'll try to apply the workaround used in the linked issue in two more places (import runs on CLI seem to also be affected), we'll see...

**Comment by Thomas-Gelf** [comment]
@briansumma: could you please give the fix I pushed a try?

**Comment by briansumma** [comment]
@Thomas-Gelf I've been running the fix all morning and I have not been able to reproduce the original error since.

**Comment by Thomas-Gelf** [comment]
Glad to hear that, thank you!
