### ISSUE TITLE
Conditional setting of variables in checks

### ISSUE THREAD

**Issue by MittelBiest09** [Icinga/icingaweb2-module-director#1072]
## Expected Behavior

In my oppinion it should be expected, that conditions with if/else statements work the same way as in the original Icinga2 configuration. At the moment there is no way to add statements in a service configuration (or at least there is no easy to find one).

## Codeexample

My hosts have some custom variables set, that would allow different behaviour of checks. As example lets say the host has the disksize for all mounted volumes as custom attribute:
vars.sda1_size = $generic_value

In the my check i want to have the option to tell my system the following:
if (sda1_size < $threshhold){
    disk_wfree = 10%
}else{
    disk_wfree = 20%
}

I have tried serveral other methods with Datalists and fields, but nothing seems to work satisfiing. In my case i would use this in combination with apply for to get checks for all partitions with custom threshholds for each partition depending on its size.
If I have overlooked the obvious in my 10+ hours of searching and trying things out i apologyze and am happy for any help in that regard.
## Your Environment

* Director version (System - About): 1.3.1
* Icinga Web 2 version (System - About): 2.3.4
* Icinga modules: Cube: 1.0.0, fileshipper: 1.0.0
* Icinga 2 version (`icinga2 --version`): v2.5.4 ()
* Operating System and version: SLES 12-SP2

**Comment by Thomas-Gelf** [comment]
Hi @MittelBiest09,

you can create a command, define an Argument of type Icinga DSL and define this condition there. Should work since the very early releases of the Director, have a look at #496 for a related example. DSL in Objects or Custom Variables will not happen very soon. There are still too many unanswered questions related to Cluster Sync, state persistance and DSL serialization in Icinga 2. Therefore the Director will remain a little bit conservative when it goes to DSL usage. But you should easily be able to solve your example and much more complex ones by putting that logic into your commands.

Cheers,
Thomas

**Comment by Thomas-Gelf** [comment]
One more hint, given your argument is `--warning` set it's DSL body similar to:

```
if (macro("$disk_size$") < macro("$threshhold$")) {
    return "10%"
} else {
    return "20%"
}
```

**Comment by MittelBiest09** [comment]
Thanks alot. I will have a look into that :)
