### ISSUE TITLE
Deployment zone of UserGroups can't be changed

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#1163]
I'm able to define a cluster zone for Users with the setting in the User Template, fine. But it's not possible to change the cluster zone for UserGroups.

# Environment

Director version (System - About): master, Git commit: 424fc31
Icinga Web 2 version and modules (System - About): 2.4.1
Icinga 2 version (icinga2 --version): r2.7.0-1
Operating System and version: CentOS Linux release 7.3.1611 (Core)
Webserver, PHP versions: Apache, PHP 5.4.16

**Comment by Thomas-Gelf** [comment]
@mwaldmueller: currently this isn't there, as it is VERY easy to shoot yourself in the foot with this. Of course it could be added easily. May I ask for your motivation for this?

**Comment by mwaldmueller** [comment]
Okay, I found a workaround for this in my scenario, so that I completely avoid Users with UserGroups on satellites in separated zones.

I would suggest to keep this issue as a reminder for future tasks...

**Comment by tobiasvdk** [comment]
It probably would make sense in a multi-tenant scenario where a group of people only manages one zone.

**Comment by wciibb** [comment]
Hi,

I've got a new thought on this matter:

I recently discovered that the inability to change the usergroups deployment zone makes my icinga2 windows agents unrestartable every time I deploy a new configuration with the director.

I configured a user and a usergroup for notification. Then I deployed this config. My Agents are syncing the configuration from the icinga server. Now most of the configuration is synced. So the users.conf is synced to the agents. The user object itself refers to the usergroup defined in the usergroups.conf. Unfortunately the usergroups.conf is never synced to the agent.

This leads to the following error message in the icinga2 service:

```
critical/config: Error: Validation failed for object 'master_admin' of type 'User'; Attribute 'groups': Object 'monitoring_admins' of type 'UserGroup' does not exist.
Location: in C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf: 12:5-12:36
C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf(10):     import "Monitoring-Admin"
C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf(11):
C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf(12):     groups = [ "monitoring_admins" ]
                                                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf(13): }
C:\ProgramData\icinga2\var\lib\icinga2\api\zones/director-global/director/users.conf(14):
```

Now you're not able to start or restart the icinga agents service again until you've completely deleted all of the synced configurationfiles in C:\ProgramData\icinga2\var\lib\icinga2\api\zones\director-global.

Everytime you restarting your agents machine you have to do this, which is somewhat unfortunately.

I researched in the director with the preview feature of the user and the usergroup an found that the users deployment zone is director-global and the usergroups deployment zone is the icinga server itself:

```
zones.d/icingasrv/usergroups.conf
object UserGroup "monitoring_admins" {
    display_name = "Monitoring-Admins"
}

zones.d/director-global/users.conf
object User "master_admin" {
    import "Monitoring-Admin"

    groups = [ "monitoring_admins" ]
}
```

I tried a workaround in manually copying the usergroups.conf into the director-global dierctory on my icinga server. This made the usergroups.conf appearing at the agents and I was able to restart the service successfully.

But when you next deploy a new director configuration the conf disappears on the icinga server's director-global and in the follwing sync on the agent also resulting again in the situation that the agents service is not restartable anymore until you either add the conf on the icinga server or delete the synced configuration from the agents directories.

I think the abillity to change the deployment zone within the director would solve this cumbersome situation, wouldn't it?

generally really much thanks for the director and the work at all - it's my favorite way for configuring icinga2 by now. I didn't touch any configfile with vi since then ... :-) 

Regards,
Heiko

**Comment by MarcusFinger** [comment]
Hello,

we also have the requirement to configure usergroups with director into a global zone (in our environment "director-global"). 

Currently all usergroups are placed into zone "master", which is the zone of the director host and which is not global.
All satellite-zones do not know about this usergroup. Therefore usergroups cannot be used in notifications for the satellite zones. We are using these kind of notifications because we have dedicated users to satellite zones (like Tobias mentioned before).

We would need the possibility to configure usergroups in a global zone with director.

Regards
Marcus

**Comment by pogii123** [comment]
+1

**Comment by Thomas-Gelf** [comment]
Implemented - be careful with this
