### ISSUE TITLE
Allow to offer choices only based on a specific import

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1178]
A property named `required_template_id` or similar should show choices only for objects inheriting that template.

**Comment by Copis** [comment]
That would help to create customized templates regading diferent types of devices or values into some hostgroups

**Comment by orbison** [comment]
I am afraid that the addition of the **Associated Template** field to the **Host template choice** definition will break the configuration scheme that I use at several customer installations.

Among other things I use the host template choices to let the user choose at which location a given host is. Due to the change introduced by commit 121dd774c the location template choice must now be associated with only one particular host template, right? However, no such template is always available. I can imagine creating a host template named "host which is located somewhere", but that's kind of superficial and prone to errors (users won't remember to always import such a template).

Another example is the choice of an operating system. There are many different devices running the same kind of operating system (e. g. IOS-XE or Linux). Before 121dd774c the user could choose whatever operating system was available no matter which templates the host inherited from. Now there will have to be one extra template which will have the OS template choice associated with and all devices will have to inherit this template. Or am I missing something? :-)
