### ISSUE TITLE
Arguments in Command can not be added as Fields

### ISSUE THREAD

**Issue by mikeb93** [Icinga/icingaweb2-module-director#1191]
I just created a new command. After adding all the necessary arguments in the arguments tab I am not able to add them as fields to the command.

## Expected Behavior

Created arguments for a command should be available in the Fields tab so they can be added to the command for use.

## Current Behavior

Arguments are not available in the Fields tab. They don't show up. They don't show up in icinga director -> custom variables either.

## Steps to Reproduce (for bugs)

1. create a new command
2. add arguments in the arguments tab
3. try to add them as fields in the fields tab

## Your Environment

* Director version (System - About): latest master from github
* Icinga Web 2 version and modules (System - About): 2.4.1
* Icinga 2 version (`icinga2 --version`): 2.7.0-1
* Operating System and version: Ubuntu Server 16.04 LTS
* Webserver, PHP versions: apache 2.4.18, php 7.0.22

**Comment by Tripoloski** [comment]
Exact the same here.

>> My workaround: clone another custom added command, change path, name and attributes -> attributes are available in fields - tab. <<
Works like a charm. Even deployment..

Icinga2: r2.6.3-1
Icingaweb2: 2.4.1-1
Director: git clone master from 29. august 2017
OS: ubuntu server 16.04.3 LTS
Apache2: 2.4.18
Php: 7.0.22

**Comment by Thomas-Gelf** [comment]
Works just fine here - or I didn't really get the problem. Could one of you please share some related screen-shot to help me understand what's going on?

**Comment by Tripoloski** [comment]
Ok.. thats really strange.. i restarted everything. the apache, mysql, php i have deleted all caches and tried it several times with different check-names check-paths and different names for the attributes. 

Now i wanted to make the screenshots you asked for and now its working.. 
I was confused anyway because on friday everything worked fine and we do not changed something over the weekend. No updates, nothing. Know its working again.

Should i share some data anyway?

And thank you for the fast response!

**Comment by Thomas-Gelf** [comment]
@Tripoloski: glad to hear that it works! And yes, strange. No idea what other information I could ask for, sorry. Some thoughts:
* in theory, opcaches or similar should be fine a (very) few seconds after you change files on disk, so in case you upgraded Director and there would have been such a bug - it could have been that it was still there for a short time after your upgrade. Just: I do not remember to have fixed anything related.
* MySQL caches would never have an impact here
* check-names and -paths are not related
Could it eventually be that you used just `varname` or `$varname` instead of `$varname$` as the arguments value?

Cheers,
Thomas

**Comment by Tripoloski** [comment]
I think i figured it out..

![bildschirmfoto 2017-09-18 um 11 53 55](https://user-images.githubusercontent.com/32058896/30537144-de3ba660-9c68-11e7-8440-4931188b1186.png)

![bildschirmfoto 2017-09-18 um 11 54 04](https://user-images.githubusercontent.com/32058896/30537154-e5c2139c-9c68-11e7-9bb3-a86a7464c655.png)

![bildschirmfoto 2017-09-18 um 11 54 15](https://user-images.githubusercontent.com/32058896/30537158-e8df6ea8-9c68-11e7-815c-ff88a33a4351.png)

Is there maybe a problem with "-" in attribute-value ? Or am i stupid because i have to RTFM? 

Cheers

**Comment by Thomas-Gelf** [comment]
@Tripoloski: thanks, this helps. While seeing `-` in variable names feels little bit strange, it is perfectly valid in Icinga 2. Director tries to extract macro strings in a best effort manner, and suggests what it finds. I'll relax that code to allow for all potential variables. As a workaround in the meantime in such a case it is perfectly valid to manually create new custom vars through Dashboard -> Define Data Fields. Afterwards, you can add them as fields to your commands. A little bit annoying, but it works.

**Comment by Thomas-Gelf** [comment]
Postponed, workaround exists.

**Comment by DimaBrest** [comment]
This is my story of success :-)
Adding arguments like "$UPS_status_crit$" didn't worked. Even cloning other commands not worked.
Changing those arguments (e.g. removing "_") - not worked.
But.. changing argument name to "$ups_status_crit$" (first characters lowercase) - and my arguments appeared at DataFields tab.

System configuration:
Icinga Director 2.4.2
icinga2 r2.8.0-1
Ubuntu Server 16.04.3 x64

**Comment by mikeb93** [comment]
Im closing this as this issues hasn’t appeared on current versions.
