### ISSUE TITLE
Data fields form requires data target type for data list entries, but not documented/explained

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2-module-director#1264]
#1080 added the possibility to select a target type for data lists.

This is somewhat confusing when you just want to add a data field.

## Expected Behavior

There should be a default value, if the the user doesn't know what this is.

The documentation should explain it too, the screenshot there is outdated.

## Current Behavior

You are forced to select a target type value, but it is hard to tell which implication each type has.

(unless you are an experienced Director user, or a developer)

## Possible Solution

Provide tooltip/help in the form.

Update the documentation.

## Steps to Reproduce (for bugs)

1. Create a new data list
2. Create a new data field with the data type `datalist`
3. Select a data list
4. `Target data type` is required, but not explained

<img width="1002" alt="screen shot 2017-10-28 at 16 39 05" src="https://user-images.githubusercontent.com/382049/32135415-4ec80f08-bbff-11e7-851f-04784923d87b.png">

## Context

Creating a datalist with values is part of the Icinga training, and we experienced this new required item during the training (participants might add their thoughts into this issue too).

Imho data fields and data lists are for more advanced usage. Still you need such capabilities in order to assign special values to check commands, e.g. array types or specific drop down lists filled with datalist entries.

It gets complicated when you need to first create the data list, and then add this as a new data field being somehow blocked what the target data type now is.

The data list seems to be a hash with key value pairs, this added another complexity when choosing the target type being a string or an array too. 

We've looked into https://www.icinga.com/docs/director/latest/doc/16-Fields-example-SNMP/ and other references too but couldn't find an explanation.

In the end, we tried to go for "String" and it worked. 

## Your Environment

* Director version (System - About): v1.4.1 (release)
* Icinga Web 2 version and modules (System - About): v2.4.2
* Icinga 2 version (`icinga2 --version`): v2.7.1
* Operating System and version: CentOS 7
* Webserver, PHP versions: Apache 2.4, PHP 5.4.16

**Comment by nodermatt** [comment]
Hi @dnsmichi I stumbled over the same thing as you and intuitively selected "String" as the target data type as well. While that was fine for me, it seems that even though the display of the select value from the datalist works fine, internally not the label of the entry but its key is saved.

![image](https://user-images.githubusercontent.com/1467464/45033783-dcec9100-b055-11e8-9986-ff9babbf097b.png)

I configured a custom command that defines check_snmp as follows:

    check_snmp_mem.pl -H $host.address$ -l $host.vars.snmpv3_user$ -x $host.vars.snmpv3_auth$ -L $host.vars.snmpv3_authprot$,$host.vars.snmpv3_privprot$ -w70,70 -c080,80

From my expectation (and host template definition ) this should render to the equivalent of the following:

    $ /usr/lib/nagios/plugins/check_snmp_mem.pl -H "host" -l cssup -x authpw -X privpw -L SHA,DES -w70,70 -c080,80

However, when I inspect the command in the host view, I can see that -L shows "2,2" instead of SHA,DES.

    '/usr/lib/nagios/plugins/check_snmp_mem.pl' '-H' 'host' '-l' 'cssup' '-x' 'authpw' '-L' '2,2' '-C' 'public' '-H' -X 'privpw' '-c' '70,70' '-f' '-t' '5' '-w' '80,80'

When I change the target data type of the autprot and privprot datalists to "Array" instead, Icinga shows an error when I run the check_command:
![image](https://user-images.githubusercontent.com/1467464/45034390-afa0e280-b057-11e8-8aed-314c20df5f4f.png)

Did you come across using the custom fields as variables (for example: $snmpv3_authprot$) as well?

PS: In the meantime I will go for hard-coding the aut and privprot.

**Comment by Thomas-Gelf** [comment]
Some inline hints should help here. Target data type refers the Data Type of the target variable, read: whether the created Custom Variable should be a string or an Array. In addition, in this ticket I see some confusion regarding Data Lists in this context. Every entry has a key and a label, with the label being presented to the user and the key being persisted to the custom variable. In case this is the same, just write the same. So in above example: AES => AES, DES => DES.

In the linked documentation example we're using 1 => SNMPv1, 2 => SNMPv2c, ... as the plugin accepts just numbers, but in the UI we didn't want to have any doubt that it is really `2c` and not just `2`.
