### ISSUE TITLE
I'd like to create a director module for importing sources

### ISSUE THREAD

**Issue by ghost** [Icinga/icingaweb2-module-director#1344]
Hi,

I'd like to create a director module for importing data.

I'm curious if there's any developer documentation to learn how to do this.
I first tried to guess the functionality by looking at the sources of the vsphere module but I'm stuck at the very beginning. For example the configuration tab does not show up and I've no idea where the magic happens to display it. Other modules for instance are using ```$this->provideConfigTab``` on a configuration.php. Or how to use other nifty things like QuickForm.

I'd be happy to get some documentation for digging my head into :-)

Thanks so far for the great work!

Yves

**Comment by Thomas-Gelf** [comment]
There is no such documentation so far, sorry. You might have a look at the [nmap](https://github.com/Thomas-Gelf/icingaweb2-module-nmap) example, that's a very simple one. `run.php` needs to provide your hook. Optional second parameter might be the full class name in case it's not the one following our generic Icinga Web 2 hook conventions.

You need to extend `ImportSourceHook` and implement `fetchData` and `listColumns`. `listColumns` is optional, but strongly suggested - otherwise Director needs to fetch all your data every time you tweak a Sync Property. In case your source needs configuration you can implement `addSettingsFormFields`.

Just have a look at the various examples in our published modules or even in the Import Sources provided by the Director, they all make use of this hook.

Cheers,
Thomas
