### ISSUE TITLE
Applied services: Rules using Assign where ... is true (or set) are not displayed in services tab

### ISSUE THREAD

**Issue by 3it-n** [Icinga/icingaweb2-module-director#1387]
## Current Behavior
Applied services which use the rule "Assign where ... is true (or set)" were not displayed in the services tab of hosts. Nevertheless they get applied and the checks are executed correctly.

## Your Environment

* Director version (System - About): current master (20180210)
* Icinga Web 2 version and modules (System - About): 2.5.1
* Icinga 2 version (`icinga2 --version`): 2.8.1-1
* Operating System and version: Ubuntu 16.04.3 LTS
* Webserver, PHP versions: apache-2.4, PHP 7.0.25-0ubuntu0.16.04.1

**Comment by Kaelnor** [comment]
I can confirm this behavior running the same environment. 

## Steps to reproduce

I defined a data field "partitions" of type Array that I associated in a host template "Linux Host".

Here is an example of a host inheriting this template:

```
object Host "www.cms.dc2.mngt.io" {
    import "Linux Server"

    display_name = "www.cms.dc2.mngt.io"
    address = "www.cms.dc2.mngt.io"
    vars.os = "Linux"
    vars["os.distrib"] = "Ubuntu"
    vars["os.version"] = "14.04"
    vars.partitions = [ "/", "/home", "/var" ]
}
```

Then, I created a service template "Partitions" using the default "disk" check command with all variables defined as fields to be able to override them.

This template is then applied this way:

```
apply Service "Partitions" for (config in host.vars.partitions) {
    import "Partitions"

    assign where host.vars.partitions
    vars.disk_partitions = config

    import DirectorOverrideTemplate
}
```


The result is that the services are correctly applied for each partition defined on the host and are checked by Icinga:

![capture d ecran 2018-03-23 a 17 21 03](https://user-images.githubusercontent.com/5421003/37840946-ae3dcbbc-2ebe-11e8-9e77-d36f8d89bb4e.png)

_By the way, there is a missing space between the template name and the object name as 'Partitions/' should be 'Partitions /'_

But, the services are nowhere to be seen on the Host configuration > Services tab:

![capture d ecran 2018-03-23 a 17 23 53](https://user-images.githubusercontent.com/5421003/37841095-1aa76394-2ebf-11e8-92fc-f2359dceae14.png)

## Expected behavior

My original goal was to reproduce the default configuration shipped with icinga2 packages, these parts in particular:

```
object Host NodeName {
  /* Import the default host template defined in `templates.conf`. */
  import "generic-host"
 ... 
  /* Define disks and attributes for service apply rules in `services.conf`. */
  vars.disks["disk"] = {
    /* No parameters. */
  }
  vars.disks["disk /"] = {
    disk_partitions = "/"
  }
```


```
apply Service for (disk => config in host.vars.disks) {
  import "generic-service"

  check_command = "disk"

  vars += config
}
```


Here, the applied service has all his variables correctly overridden by those defined in the host's disks dictionaries.

In the current iteration, the director doesn't allow to define dictionaries as Data Fields and services variables assigned with "Apply for" rules cannot be overridden.
