### ISSUE TITLE
Some Synchronize Rules should not create new Objects

### ISSUE THREAD

**Issue by fmuell** [Icinga/icingaweb2-module-director#1412]
## Expected Behavior

Currently we use 2 kinds of synchronize rules. The first one creates host objects with common attributes (like ip address, hostname, os etc). The second adds custom variables to modify the service monitoring (like usernames, passwords, urls).

The second type of sync rules should not create host objects which are not part of the first import. There should be a switch in the sync rule properties which allows only the modify of existings objects, not create them.

## Current Behavior

The second type of sync rule creates hosts with only the custom vars, but because they are not (longer) existent in the first sync, they have not all attributes needed for proper monitoring.

## Possible Solution

Add a switch in sync rules to prevent creating non existent objects

## Your Environment

* Director version (System - About): 1.4.3
* Icinga Web 2 version and modules (System - About): 2.4.0, director 1.43, fileshipper 1.0, monitoring 2.4.0
* Icinga 2 version (`icinga2 --version`): 2.6.1
* Operating System and version: centos 7.3
* Webserver, PHP versions: apache, php 5.4.16

**Comment by phil-or** [comment]
+1

**Comment by fmuell** [comment]
Any thoughts for this one yet?

**Comment by Thomas-Gelf** [comment]
@fmuell: whenever I have to build something similar, I use the second import to fill a Data List with values, and then I use the "Map" property modifier on the first import to get related properties from that list if available. This is the preferred way especially when the second import contains objects the first one doesn't know about - otherwise one might also want to combine multiple sources in a single sync rule.

**Comment by fmuell** [comment]
Thanks for the feedback. I will try it out soon

**Comment by Thomas-Gelf** [comment]
This has been implemented for v1.8.0
