### ISSUE TITLE
Do not store API User Passwords in Cleartest

### ISSUE THREAD

**Issue by mzhaase** [Icinga/icingaweb2-module-director#1491]
Director 1.4.0

icinga_apiuser table stores passwords in cleartext. This should most definitely not be the case.

**Comment by Thomas-Gelf** [comment]
Please configure your database to use data on rest encryption. Director needs the clear password, otherwise it wouldn't be able to connect. Encrypting just the password would of course be easy. However, Director would then need to have the related key - so you would just move the problem.

Certificate-based authentication will be implemented and should then become the default authentication method. But once again, the same problem will then apply.

**Comment by mzhaase** [comment]
Ah, it needs it to connect to other nodes, I see.On May 17, 2018 15:10, Thomas Gelf <notifications@github.com> wrote:Please configure your database to use data on rest encryption. Director needs the clear password, otherwise it wouldn't be able to connect. Encrypting just the password would of course be easy. However, Director would then need to have the related key - so you would just move the problem.
Certificate-based authentication will be implemented and should then become the default authentication method. But once again, the same problem will then apply.

**Comment by Thomas-Gelf** [comment]
@mzhaase: I'll close this issue, in case you have more related question please do not hesitate to re-open this or a new one.
