### ISSUE TITLE
Blacklist a service from service set for a specific host fails

### ISSUE THREAD

**Issue by TobiasKneidl** [Icinga/icingaweb2-module-director#1519]
## Expected Behavior
If I blacklist a service from a Service Set, it should completely ignore this service for the specific host.

## Current Behavior
If I have an overriden Variable, the overridden Variable is dropped and the changes are shown under the activity log, the service is applied with the original variable but the service is not be ignored.

If I don't have a overriden Variable and blacklist the service, no changes are shown under the activity log.

Could I have misconfigured/misunderstood something?

## Your Environment

* current master cdcf995
* Icinga Web 2 version 2.5.3
* Icinga 2 version 2.8.4-1
* Ubuntu Server 16.04
* PostgreSQL  9.5.13
* PHP 7.0.30-0ubuntu0.16.04.1
* Apache/2.4.18 (Ubuntu)

**Comment by TobiasKneidl** [comment]
Just tested the same with a service from a Service Apply Rule:
Also no changes in activity log but if i "Deploy anyway" the service gets ignored. But not a blacklisted service from a Service Set.

**Comment by TobiasKneidl** [comment]
Also in the Services Overview, only the blacklisted Service from Apply Rule is strikethrough. The blacklisted Service from Service Set not.

**Comment by lazyfrosch** [comment]
I noticed the same behavior, it seems like blacklisting is not checked for services that are part of a set.

**Comment by dgoetz** [comment]
Hitting the Blacklist button for a Service from a Set adds an entry for the Template used instead of the Service into the database table. After I changed it in the database, it is correctly striked through and ignore is rendered, but clicking on the service does not allow to revert blacklisting now but still shows the override and blacklist options.

**Comment by rojobull** [comment]
I have noticed this as well.

**Comment by rojobull** [comment]
I know this issue is close but it has caused a problem for me after updating to 1.5. One of my service templates has an "ignore where" line as dgoetz indicated above. This is causing my deployments to fail so I can't push out any changes. Any idea how to remove that line from the service template? @dgoetz can you tell me how you removed it from the database? I will need to do the same.

**Comment by dgoetz** [comment]
I noticed the problem directly and changed the number as it was correct and worked with the database directly until the problem was fixed. You can simply drop or change the line from the database and it should not cause any problems.

**Comment by rojobull** [comment]
ok thanks. blacklisting seems to be working fine now on version 1.5.1.
