### ISSUE TITLE
import of datafields to director

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-director#1523]
## Expected Behavior
I want to import datafields to the director using a syncrule.

## Current Behavior
I cannot import datafields to the director using a syncrule.

## Possible Solutin
Allow to select "data field" as object type in sync rule.

**Comment by Thomas-Gelf** [comment]
We're getting closer. Export on CLI is there, Import not yet - and more comes soon. Data Fields are nothing that should be subject to continuing Import/Sync like Host objects, so I'm not even sure if I want to provide that possibility. I'll close this in favor of  #1630. When it's done, and in case it doesn't fit your needs feel free to ask again. Because once the basics are implemented, offering the Sync possibility is going to be a trivial joke.
