### ISSUE TITLE
1.5.0 Release Date?

### ISSUE THREAD

**Issue by Mikesch-mp** [Icinga/icingaweb2-module-director#1587]
Its now over a year that 1.5 was anounced, can we expect a release this year or do we ride a dead horse?

**Comment by Thomas-Gelf** [comment]
Don't worry, the horse is still alive :carousel_horse: :horse_racing: :postal_horn:

Sorry for the delay, release had been scheduled three weeks ago, but we missed that date. Throughout the last months the time granted to work on the Director has mostly been sponsored by customers focusing on new features rather than on getting a new release tag. Same goes true for this week. After some weeks dedicated to other Icinga-related projects, I'm now once again allowed to work on a Director feature related to working with multiple Director instances.

Eventually there will remain some time to tag a release by the end of the week, we'll see. I hear you. The master is pretty stable, there isn't be much that should hinder us from tagging v1.5.0.

And, more good news: new manpower has been dedicated to this project, in future @lazyfrosch will be granted more time to work intensively on the Director.

**Comment by Thomas-Gelf** [comment]
We'll try to target the 10th August, 2018.

**Comment by Thomas-Gelf** [comment]
It's too late for today, scheduled for Monday morning.
