### ISSUE TITLE
Bring back our loop detection

### ISSUE THREAD

**Issue by Thomas-Gelf** [Icinga/icingaweb2-module-director#1631]
## Expected Behavior

When creating loops I want the fancy loop detection we had in v1.2.0 to protect me:

![Loop detection](https://www.icinga.com/wp-content/uploads/2016/11/director_loop_detection.png)

## Current Behavior

Depending on system and context: loop is persisted, cleanup in the UI not possible, errors are timeouts and/or out-of-memory.

**Comment by rgevaert** [comment]
+1

I was just giving a training on the usage of the director and 4 out of 10 participants when starting out with the director had this problem. As you will know getting into the situation leads to a out of memory error. Which can't be fixed with adding memory to php and the vm. You need to get into the mysql database and delete the relevant inheritance rules.

It would be nice if this would be fixed soon than later :).

**Comment by deoliroe** [comment]
Happy New Year @Thomas-Gelf & all!
Would be great, prevent stupid things from being done. ;)

**Comment by Thomas-Gelf** [comment]
v1.6.1 is due tomorrow, let's see whether we can fix this in time. @jschanz: challenge accepted ;-)

**Comment by Thomas-Gelf** [comment]
### Object inheriting looping templates
![looping_object-error](https://user-images.githubusercontent.com/553008/52740691-e2221480-2fd3-11e9-83a3-9c3cb0484a6d.png)

### Looping template, it is possible to fix it
![looping_template-edit](https://user-images.githubusercontent.com/553008/52740692-e2baab00-2fd3-11e9-80d2-3477e1190561.png)

### Other places are protected, like template usage...
![looping_template-usage](https://user-images.githubusercontent.com/553008/52740694-e2baab00-2fd3-11e9-9eaa-f92d59d7e072.png)

### ...and Config Deployment
![looping_deployment-error](https://user-images.githubusercontent.com/553008/52740690-e2221480-2fd3-11e9-8f83-aa201efb8de4.png)

Will immediately be pushed to master and ported to `support/1.6`.
