### ISSUE TITLE
Trying to set invalid key flapping_threshold

### ISSUE THREAD

**Issue by aberfeldy** [Icinga/icingaweb2-module-director#1652]
## Expected Behavior
After defining an import source I'd expect that hosts get imported from the CoreAPI. 

## Current Behavior
On executing the import, it fails with "Trying to set invalid key flapping_threshold" and nothing is imported. The preview tab shows a PHP error stacktrace

## Steps to Reproduce (for bugs)
Create a new import source, set type to CoreAPI, object-type to host and check for changes.

## Your Environment
* Director version (System - About): 1.5.1
* Icinga Web 2 version and modules (System - About): 2.6.1
* Icinga 2 version (`icinga2 --version`): r2.9.1-1
* Operating System and version: CentOS 7.5.1804
* Webserver, PHP versions: apache, rh-php71

**Comment by greenberet7** [comment]
### Same issue here
I have exactly the same issue.
I can't find the flapping_threshold attribute on a host in the database but when I query a host object over the API I get following attributes related to flapping:

"enable_flapping": false,
"flapping": false,
"flapping_current": 0,
"flapping_last_change": 0,
"flapping_threshold": 0,
"flapping_threshold_high": 30,
"flapping_threshold_low": 25,

I guess the Director tries to import the flapping_threshold attributes and fails because it is deprecated (since Icinga release 2.8.0). I can reproduce the error the same way @aberfeldy explained.

### My environment:
Director version (System - About): 1.5.1
Icinga Web 2 version and modules (System - About): 2.6.1
Icinga 2 version (icinga2 --version): r2.10.0-1
Operating System and version: CentOS 7.5.1804
Webserver, PHP versions: apache, rh-php71

**Comment by teadur** [comment]
https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/Core/CoreApi.php#L484 commenting that out is ugly hack if you want to get further and don't care about flapping

**Comment by b33rcity** [comment]
> https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/Core/CoreApi.php#L484 commenting that out is ugly hack if you want to get further and don't care about flapping

I just tried replacing that line with 
```

            #'flapping_threshold'    => 'flapping_threshold',
            'flapping_threshold_high'    => 'flapping_threshold_high',
            'flapping_threshold_low'    => 'flapping_threshold_low',
```

and amazingly my Icinga2 testing node didn't catch on fire. It even shows output in the preview tab!
