### ISSUE TITLE
Director 1.6.0 allows creating duplicate Service Apply Rules, causing invalid configuration

### ISSUE THREAD

**Issue by jwilliams-shadowsoft** [Icinga/icingaweb2-module-director#1755]
## Expected Behavior
The Director web interface and API should both prevent the creation of duplicate named Service Apply Rules.

## Current Behavior
When creating Service Apply Rules there is no check to prevent duplicate named rules (or it does not work). This is true in both the web interface and the Director API. The resulting configuration will not pass a syntax check, yielding an invalid configuration.

## Possible Solution
The code for Service Apply Rules should be changed to prevent duplicate named rules.

## Steps to Reproduce (for bugs)
1. Icinga Director => Services => Service Apply Rules => Add
2. Create a rule
3. Create another rule with the same name
4. Activity Log => Deploy pending changes
The configuration is now invalid and the changes just made need to be reverted.

The identical situation can be created using the Director API.

## Your Environment

* Director version (System - About): 2.6.0
* Icinga Web 2 version and modules (System - About): 2.6.0 - director, doc, monitoring
* Icinga 2 version (`icinga2 --version`): 2.10.2
* Operating System and version: Centos 7
* Webserver, PHP versions: httpd-2.4.6, rh-php71-php-fpm-7.1.8

**Comment by Thomas-Gelf** [comment]
While I'd love to prevent this, per design it's not possible - having two Apply Rules with the same name is absolutely legal in Icinga 2. When both rules match the same Host, you'll have a collision - and the config will not be accepted. But apart from this, there is no constraint regarding Apply Rule names.

**Comment by zmaupin-do** [comment]
The bug still remains. I have the exact same configuration for the apply rule, we'll call it `check_disks` and it applies where `host.address = *`. The duplicate is still created and then configuration deployment fails because the duplicate record was allowed to be created.

**Comment by zmaupin-do** [comment]
@Thomas-Gelf 

Can you explain what makes that legal vs service templates or service groups? To me, an apply rule should fall in the same bucket. An apply rule in itself lends towards not having to declare the same apply rule more than once with OR/AND/NOT statements in the assign where field. If a user wants to create multiple apply rules for the same service, then unique names would be even more important - `check_disks` for mail servers vs `check_disks` for database servers is confusing. Why not require unique names like `mail_servers-check_disks` or `db-check_disks`?

In what cases would someone want to have a duplicate apply rule name? In what cases do service templates/service groups differ from apply rules to the point where you can have apply rules with the same name yet templates and groups require unique names?

**Comment by zmaupin-do** [comment]
I think that further proves my point. You have two service templates, with different names, each with a different type of service (one is telnet and one is snmp). Then you apply the two completely different services using the same name. Why not use the same name as your template? This does not scale well or lend toward successful automation of an Icinga2 environment. It doesn't seem like much to ask to keep the rules the same for all service object types.

**Comment by wols** [comment]
Not quite like that. My service is the _signal level_, not Telnet or SNMP!
Whether signal_level_old or signal_level_new is used is irrelevant. They are only a means to an end.

**Comment by wols** [comment]
I understand your view. That can become questions of faith ;-)
I use the described construct for abstraction levels.

> Who cares what the apply rule name is...

Me! Because the name is in the list. He is the OK, WARNING or CRITICAL.

**Comment by leprasmurf** [comment]
Whether a naming constraint is useful or not aside; my big issue is that the output of legitimate director configuration is producing an invalid icinga2 config.

> When both rules match the same Host, you'll have a collision - and the config will not be accepted.

Can director catch the collisions and handle them better?    Highlight the issue in the web UI?

Alternatively, providing an API endpoint to query for apply rules by name would allow us to check if the rule exists before creating a new one with automation.

**Comment by zmaupin-do** [comment]
I don't see how faith is involved :smiley: 

I have data showing this is a problem. Via API or Web UI, clone your record, this is allowed although the config is invalid. Then try to deploy, now your config is broken. :face_with_head_bandage: 

Any time our automation runs the apply rule is duplicated because we have no method to verify in Icinga2 that an apply rule already exists (by name or by duplicate configuration).

We don't have to enforce the naming scheme changes to fix this. Adding a check prior to adding the apply rule that verifies it _is not_ a duplicate would resolve this and we'd both be happy.
 
Another option that would satisfy us both is simply adding a `display_name` field to apply rules and enforcing the same naming conventions as templates and groups.

**Comment by Thomas-Gelf** [comment]
Wow, there is a lot of discussion going on here :-) First, let me refresh some basics:

* Template names are unique. `object Service "a" { import "b" }` would obviously become tricky if there where two instances of `b`
* Apply Rules are not real object types in the Icinga 2 DSL, technically they are just a **(for) loop**
* Apply Rules themselves do not have a name, for the Icinga Core they do not even exist after starting up. They generate services based on there own virtual `name` property.

Said all this, let's have a look at a simple example:

```
apply Service "a" { vars.warn = 10; assign where host.name == "local" }
apply Service "a" { vars.warn = 20; assign where host.name != "local" }
```
These are two Apply Rules with the very same name, there will be no conflict. Such configs are pretty common. You start with an Apply Rule for all Hosts. After some time you realize that some hosts are different. You clone the rule and define different properties for Services on different Hosts. That's perfectly legal, it should be done like this.

But as soon as someone also adds this one...

```
apply Service "a" { vars.warn = 10; assign where host.address == "192.0.2.7" }
```

...there MIGHT be a conflict. As of today, Director completely ignores this. It renders the requested config, if it conflicts nothing bad happens: Icinga continues to run, the Director Health Check notifies that (automatic) Deployments stopped working. You'll see the startup error in the UI, it will point you to the conflicting rules.

I understand that this might be annoying if you haven't been the one adding that new wrong Rule. Your very own pending change is going to be delayed because of someone else's fault. So, what can the Director do to help here? It could evaluate every existing and your new/modified Apply Rule and run it against every single one of your Hosts to check for conflicts. There could be tens of thousands of hosts.

But it doesn't stop here. The Apply Rule might run fine when you create it, but it might result in a collision years later once someone changes a specific Host property. Happened to me a few days ago: 4k+ Hosts driven by Puppet, the Kubernetes Hosts where not. Long time ago someone decided that ALL Hosts should have a "CPU" and a "Memory" check. There was an Apply Rule matching a few Windows Hosts and another one assigned `where vars.kernel == "Linux"` for every such service, of course running completely different things on Linux. As there was no Puppet in their Kubernetes World this Apply Rule didn't match, someone cloned it and created a rule based on other properties.

Everything is fully automated, Facts are synchronized from PuppetDB to the Icinga Director, automated Deployments usually take place every 15-30 minutes - lot's of changes going on all day long. Was fine for half a year. Then last week someone deployed Puppet on one of the Kubernetes Hosts. Suddenly, two Apply Rules matched - conflict, Deployment failed.

It's hard to tell who to blame in that scenario. And at what moment in time should the Director catch this error? When synchronizing from PuppetDB? Re-checking hundreds of Apply Rules every time? There are 100k+ Services, about 7-80k of them are generated via Apply Rules, the rest are Single Services imported/synchronized from various sources. All of them could potentially conflict with an Apply Rule (of the same name). It get's even trickier with `apply for` Rules, as their name usually derives from matching Host properties.

Please let me know your thoughts on this, if you have any idea of how to improve this with reasonable effort I'd love to implement it. Independent from this, please note that the following is planned:

* there will be a new mandatory background Daemon for the Icinga Director, replacing the current optional "Jobs" daemon
* we'll delegate time-consuming tasks from the frontend to that daemon
* currently there are a bunch of caching strategies, some running at Sync time, others persisted in the DB... caching is complicated
* there will be many more such tables, I want to see all Hosts and Services fully resolved in the DB
* changes in the UI will mark objects as dirty, the background daemon will take care of recalculation where necessary

Once we have all this, we'll have many more possibilities to catch duplicates. But even then, what do you think should happen in the scenario I've met last week? Or do you have different, better proposals? If so, please let me know!

Thanks,
Thomas

**Comment by zmaupin-do** [comment]
Thank you for taking the time to lay out a detailed explanation. That makes more sense now.

I do have one thing to ask. I now see why enforcing naming conventions on apply rules will not work - you've cleared that up for me. However, we still do not have a way to view apply rules via API. If given this, we can do our own verification in our deployment code. Is that something that can be put on the table?

**Comment by leprasmurf** [comment]
Thomas,

Thank you for the information, it has really helped to put the issue into better perspective.

Am I correct that when puppet was deployed on your kubernetes hosts, and automated deploys were interrupted, your production monitoring was unaffected?  I'm guessing the fix for that situation was to disable the extra kubernetes-specific apply rules and redeploy.

It's sounding like this scenario has a small blast-radius (confined to deploys), can be resolved fairly easily with manual intervention, but automatic remediation is less trivial.  This leads me to better understand why Director neglects collision detection all together.  The deploy is the test.

I like the planned features.  Delegating blocking tasks to a background runner will help with the UI responsiveness (I'm looking at you long-running sync rules).  Having the hosts fully resolved in the database would absolutely help in the collision detection.  And the object marking strategy is reminiscent of garbage collection 👍 .

I've given your questions some thought and my proposal is below.  As a preface I will say that I lack sufficient insight into director's workings to fully and accurately state the feasibility of its implementation.

Detection is happening already during deploys.  Director could render the current configuration on a cadence and test with `icinga2 daemon --config /tmp/conf.file --validate`; then interpret stdout/stderr/exit code.

I'd bet this, or something like it, is already being done in director.

With regards to remediation I think another metric is required:  an apply rule's weight.  It could be derived from the count of object a rule applies to ... and cached in the db 😄 

Validate
When a collision is detected between two rules compare the rules.
If rules are equal:  disable lighter weight rule.
Else exclude lighter weight rule's match from heavier rule.
GOTO 10

Regards,
Tim

**Comment by Thomas-Gelf** [comment]
@zmaupin-do: not sure whether I understood what you're talking about. Do you want to work with Apply Rules via REST API?

**Comment by zmaupin-do** [comment]
@Thomas-Gelf yes that is correct. It would be great, at a minimum, to be able to list the apply rule configuration objects

**Comment by Thomas-Gelf** [comment]
@jwilliams-shadowsoft: now I got it. So your problem is not in the UI, but the fact that you're trying to deal with Apply Rules via REST. And this is of course tricky (if possible at all), as the "name" doesn't qualify as an Identifier for Apply Rules in Icinga 2. In theory you should be able to address them by ID, but I didn't try.

We faced this problem when implementing the Basket for v1.6.0. There we have to work across multiple instances, and there even the ID wouldn't qualify as an Identifier. Matching the "exact same" rule would of course be possible, but that way you cannot track any changes.

As there isn't much the Director can change about this, our current plan is to introduce Director-specific UUIDs solely for Apply Rules. Another option would be to introduce unique Apply Rule names distinct from the derived Service names. This would force one to choose a meaningful name telling you what this rule is all about for different variants of the very same applied Service definition.

Both would be pretty intrinsic changes, so this is nothing what could easily be done on the fly. If a dedicated REST API endpoint shipping all existing Apply Rules with name and ID would helpful for you, I can offer to implement such. If that's the case, please elaborate the 'option of using filters' part. What kind of filters would you need?

**Comment by zmaupin-do** [comment]
After much discussion with my team this is what we ask:

1. An API endpoint for service apply rules to GET, at least, ID and Name. We can update, replace, delete via ID once we have the ID.
  a. director/services endpoint with filters like the Icinga2 API (director/services?object_type=apply)
  or
  b. director/serviceapplyrules (Similar to /servicetemplates)

2. Enforce naming conventions for apply rules similar to the rest of the Icinga2 objects. One caveat, add a display_name field so folks like @wols will only see `signal_level` (display name) instead of the various apply rule names `signal_level_old` or `signal_level_new`.

**Comment by zmaupin-do** [comment]
@Thomas-Gelf checking in to see if you have any comments.

**Comment by Thomas-Gelf** [comment]
@zmaupin-do: this week I'll introduce a new API endpoint as suggested in 1b.

**Comment by zmaupin-do** [comment]
Thank you so much!
