### ISSUE TITLE
Undefined property in services tab

### ISSUE THREAD

**Issue by chrkli193** [Icinga/icingaweb2-module-director#1795]
## Expected Behavior
Opening the service tab in a hosts shows the assigned services

## Current Behavior
Getting an error because of an Attribute which is not set on this host because not needed.
![image](https://user-images.githubusercontent.com/16578747/53555619-95494c80-3b42-11e9-9e3b-7ebfc3d1f1ad.png)
I get this issue on all hosts where the property is not set. This property/field is set on the default template for all hosts but only shown if specific values are set. Also the service if only applied if some values are set

## Your Environment

* Director version (System - About):
* Icinga Web 2 version and modules (System - About):  2.6.2
* Icinga 2 version (`icinga2 --version`): 
icinga2 - The Icinga 2 network monitoring daemon (version: r2.10.3-1)

Copyright (c) 2012-2019 Icinga GmbH (https://icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

System information:
  Platform: Ubuntu
  Platform version: 16.04.6 LTS (Xenial Xerus)
  Kernel: Linux
  Kernel version: 4.4.0-142-generic
  Architecture: x86_64

Build information:
  Compiler: GNU 5.3.1
  Build host: fd3f712856b4

Application information:

General paths:
  Config directory: /etc/icinga2
  Data directory: /var/lib/icinga2
  Log directory: /var/log/icinga2
  Cache directory: /var/cache/icinga2
  Spool directory: /var/spool/icinga2
  Run directory: /run/icinga2

Old paths (deprecated):
  Installation root: /usr
  Sysconf directory: /etc
  Run directory (base): /run
  Local state directory: /var

Internal paths:
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

* Operating System and version:
* Webserver, PHP versions:

**Comment by wp-perc** [comment]
I am using Director 1.8, and this bug is still present.
To reproduce:
 - Create some Host Template and (if you want) some Host Object
 - Create a datafield (data type is not important, use string or number is good enough)
 - Create a Server Apply Rule or a Service Set and assign it using an Apply Rule involving the datafiled and using some numerical operator (like 'host.vars.my_custom_var <= 2')
 - Go inside a Host/Host template, change to Services tab and you get the error
 - On the same host, fill the datafield with some integer value, change again to Service tab and you will not get the error

I think is related the way the Filter operator is written, which seems to require that this property still exists.

A workaround is provide a default value for this datafield for all Host Objects, but it should not be the wanted implementation.

**Comment by bobapple** [comment]
ref/IP/33223

**Comment by Thomas-Gelf** [comment]
This fails in `Icinga\Data\Filter`. There is no fallback [here](https://github.com/Icinga/icingaweb2/blob/b2274a5/library/Icinga/Data/Filter/FilterEqualOrGreaterThan.php#L10), like it has been implemented [here](https://github.com/Icinga/icingaweb2/blob/b2274a5/library/Icinga/Data/Filter/FilterGreaterThan.php#L10).

Quick fix: apply something like [6d70572](https://github.com/Icinga/icingaweb2/commit/6d70572) for every operator in Icinga Web 2.

Sooner or later we should add a small dedicated filter library to the Director project, as we have to address slightly different requirements. Our main concern is to have all operators behave "exactly" as they do in the Icinga Core: in our "user space" (read: application code) and in our database.
