### ISSUE TITLE
Host -> Services Tab -> Add asks for templates, but form says 'service'

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2-module-director#1827]
## Expected Behavior

Tell me to import a template :)

## Current Behavior

The service object suggests to modify the `Service*` column, but actually the dropdown help suggests to use a service template.

![Screen Shot 2019-04-10 at 17 55 54](https://user-images.githubusercontent.com/382049/55894273-20921500-5bba-11e9-9b2d-764321c2b1e8.png)

## Possible Solution

Change the key text in the form.

## Steps to Reproduce (for bugs)

1. Create a host template `bp-hosts` with `hostalive`, create a host `bp-host`
2. Create a service template `bp-services` with `icingacli-businessprocess`
3. Navigate into the `bp-host` again, choose the `services` tab.
4. See the form which asks for a template with the wrong form key

## Your Environment

* Director version (System - About): 1.6.2
* Icinga Web 2 version and modules (System - About): git master, a487f83f99e440bc71e268725a31943d9e29ea75
* Icinga 2 version (`icinga2 --version`): v2.10.2-257-g856d3a1
* Operating System and version: CentOS 7
* Webserver, PHP versions: http 2.4, PHP 7.1

**Comment by Thomas-Gelf** [comment]
Sorry, I don't get the problem. You are on the Services tab of a host, click "Add Service" - and then you're asked to choose from a list of available Services. Sure, these are Templates - but we do not want to bother users with such technical details. But eventually I misunderstood your question/issue.

**Comment by dnsmichi** [comment]
The dropdown says "Choose a service template", for "Service". That's kind of irritating.

Once I select the template, the form changes, and uses the same object name from the template for the service object.

![Screen Shot 2019-04-10 at 18 04 44](https://user-images.githubusercontent.com/382049/55894835-3c49eb00-5bbb-11e9-932b-ca542edd8b97.png)

**Comment by Thomas-Gelf** [comment]
That's intentional, you're allowed to change the name of the service that should be created - the name of the chosen template is proposed as a default. I'm open for suggestions on how to improve this.

**Comment by dnsmichi** [comment]
Hi Tom,

I've thought a little about this yesterday evening, finding out what really bugs me here. In my adopted Director workflow, I'm used to the forms which require a template created before creating a service apply or set or object.

That works just fine in the forms you'll reach via menu.

![Screen Shot 2019-04-11 at 08 54 33](https://user-images.githubusercontent.com/382049/55936781-8e305680-5c37-11e9-9f04-ac06bb23f917.png)
![Screen Shot 2019-04-11 at 08 54 58](https://user-images.githubusercontent.com/382049/55936787-92f50a80-5c37-11e9-9425-de52ca8b1801.png)

I think, it irritates me that the "add service" form from inside a host object context looks different.
I'd expect to 

- set the name
- pick a template import
- set other attributes like the other forms

![Screen Shot 2019-04-11 at 08 57 45](https://user-images.githubusercontent.com/382049/55936902-e6675880-5c37-11e9-9f86-e6bb06220950.png)


I don't know why I have chosen to go this way, I just found it more quick than navigating again into the menu with apply rules :)

A few suggestions for the form, maybe you'll find them useful:

- `Add Service: <hostname>` - rename that to `Add Service for Host: <hostname>`, showing you the context a bit better. This would have shown me that this isn't the service `bp-shop` which likely irritated me at first.
- Show the full service form, including "imports" for the templates
- Propose a name, based on the chosen import, but show the `name` field immediately

Thanks & cheers,
Michael

**Comment by Thomas-Gelf** [comment]
Thanks for your sharing your thoughts, I see where you come from. 

> I think, it irritates me that the "add service" form from inside a host object context looks different.

I understand. Let me explain where this comes from and where we're heading to:

* Templates are for admins only. It's their job to nest and structure them
* "End users" (especially restricted ones) shouldn't be bothered with that complexity
* The wording "Template" should never bother them. If an admin wants to provide more flexibility, he can do so by using "Template Choices". Please see the [v1.4.0 Release Blogpost](https://icinga.com/2017/10/09/icinga-director-v1-4-0-has-been-released/) for such an example.

> I'd expect to
>     * set the name

You shouldn't be required to do so. As an admin, I opted for "CPU Load" being the name for related services. I do not want every user to be forced to invent his very own label for the very same check again and again. I would end up with lot's of Services with different names, "CPU", "cpu", "load", "System Load" and so on. Cleaning up the mess would mean losing related History in my Grapher. That's why I want to propose a default name as soon as you opt for a specific Service Template

>     * pick a template import

It will not be named "Template". The action a use is fulfilling is "Adding a Service". We'll hopefully introduce the possibility to structure Service Templates into categories, to simplify this operation even more. The user should choose Services (or Service Sets) from a catalog provided by the Icinga (Director) admin

>     * set other attributes like the other forms

Sure. However, with the restriction that not all settings are available on the single Service. You're not allowed to use potentially dangerous settings like check intervals, and you'll be allowed to fill only custom variables according the rules defined by the admin via related "Custom Fields"

> A few suggestions for the form, maybe you'll find them useful:
> 
>     * `Add Service: <hostname>` - rename that to `Add Service for Host: <hostname>`, showing you the context a bit better. This would have shown me that this isn't the service `bp-shop` which likely irritated me at first.

What about "Add Service to <hostname>"? You would otherwise run into trouble with screen width on smaller devices and long hostnames

>     * Show the full service form, including "imports" for the templates

I wouldn't do so, please see above. However, always open for other views and suggestions

>     * Propose a name, based on the chosen import, but show the `name` field immediately

I'd love to, but this is tricky. That's what I tried to accomplish initially when tweaking this form. What should I do if the user switches the template with the name field already compiled? How should he understand that skipping the name field and choosing the template first would be the way to go?

Cheers,
Thomas

**Comment by dnsmichi** [comment]
Hi Tom,

thanks for explaining, with the knowledge of restrictions this makes more sense. These are regions I have not yet covered in my "let's use the Director and explain that to users on Icinga Discourse" adventure :)

> What about Add Service to <hostname>? You would otherwise run into trouble with screen width on smaller devices and long hostnames

Yep, that would be perfect and crystal clear, thanks :)

The problem with different roles and what they see and not see is really tricky. I truly understand that you want to move away from the difference with templates (admins) and objects (admins and users), still an admin starting with small steps into the Director may find this a little irritating.

The Director pushes you to create templates before objects, which sometimes breaks a workflow with adding a host and then quickly a service. Once you have mastered that hurdle, your brain says "Hey, I've got the templates Director wants, now let's create some cool apply rules, and import the templates."

That's what I've learned, and maybe others think in the same way. Moving away from the templates you know, and making this more generic for non-admins is a good idea, but I don't know if existing admins will learn to change the thinking.

Maybe the term 'template' or 'import' doesn't explain it that good. 'Inherit from' or 'Use' sounds better? 
Given that Icinga 2 allows you to import templates and objects in both ways, it's also fine to list both in the dropdown then. Maybe sorted with the templates on top, then objects.

This might also need more opinions then, e.g. @flourish86 :)

Cheers,
Michael

**Comment by Thomas-Gelf** [comment]
> > What about Add Service to ? You would otherwise run into trouble with screen width on smaller devices and long hostnames
> 
> Yep, that would be perfect and crystal clear, thanks :)

Will be changed!

> The problem with different roles and what they see and not see is really tricky. I truly understand that you want to move away from the difference with templates (admins) and objects (admins and users), still an admin starting with small steps into the Director may find this a little irritating.

As of today, Icinga Director is a tool allowing experienced Icinga users to automate and/or delegate annoying tasks. We're aware of this initial hurdle and are working on lowering the entry bar. There will be more Director-only constructs like Service Sets (available), Template Choices (available, more features to come) and Categories (not yet). Baskets have been implemented as one of our tools to get Users started much faster. They now allow to ship opinionated base configurations with different flavors.

> Maybe the term 'template' or 'import' doesn't explain it that good. 'Inherit from' or 'Use' sounds better?

That's what their name is :D We'll not invent yet another naming, we try to completely hide those technical wordings from end users. You'll "Add a Service" and choose "CPU Load" from a catalog, that's it.

> Given that Icinga 2 allows you to import templates and objects in both ways, it's also fine to list both in the dropdown then. Maybe sorted with the templates on top, then objects.

Director strictly distincts Objects from Templates, you're not allowed to inherit from an Object. This is possible only for Commands,  as "external objects" made things a little bit complicated.
