### ISSUE TITLE
Configuration form breaks with inherits from DbConnection with Icinga Web 2 14b6e4056231e12b4826432dfd7d5c60796e08b2 

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2-module-director#1837]
## Current Behavior

Editing the Director configuration fails with recent TZ changes in Icinga Web 2.

```
Fatal error: Access level to Icinga\Module\Director\Db::getTimezoneOffset() must be public (as in class Icinga\Data\Db\DbConnection) in /usr/share/icingaweb2/modules/director/library/Director/Db.php on line 16
```

![Screen Shot 2019-04-17 at 11 47 16](https://user-images.githubusercontent.com/382049/56278602-d1db0280-6106-11e9-9724-a10257e9dcce.png)

## Possible Solution

Discuss code changes with @nilmerg 

## Steps to Reproduce (for bugs)

- Use Icinga Web 2 from snapshot packages
- Use Director (master or 1.6.2)
- Navigate into the modules section and select the `Configuration` tab inside the Director

## Your Environment

* Director version (System - About): HEAD, https://github.com/Icinga/icingaweb2-module-director/commit/d3fa347ec2aa509d2d926ff86629cb118cbaaf63
* Icinga Web 2 version and modules (System - About): HEAD, https://github.com/Icinga/icingaweb2/commit/14b6e4056231e12b4826432dfd7d5c60796e08b2
* Operating System and version: CentOS 7.6
* Webserver, PHP versions: httpd 2.4, PHP 7.1

**Comment by Thomas-Gelf** [comment]
@dnsmichi: thanks for testing/reporting this! Could you please move this issue to icingaweb2? Director introduced this fix in March 2018, a related issue for Icinga Web 2 has been created in July, v1.5.0 has been released with this fix in August. This has now also been fixed in Web 2 with the version you linked. The fix contains the very same code as the one in this module - but with public accessibility.

While having this method public might eventually be helpful, I'd opt for changing it to `protected` in Icinga Web 2. Two reasons:

* it otherwise breaks every Director release since v1.5.0
* the method does not what it suggests. It doesn't tell you what Timezone is currently configured on your DB connection. It tells you what it WOULD configure right now depending on your PHP runtime.

Therefore we shouldn't expose this method publicly on the `Db` class Api.

**Comment by nilmerg** [comment]
Dddddddouble change.
