### ISSUE TITLE
Cloning scheduled downtimes does not work

### ISSUE THREAD

**Issue by swizzly** [Icinga/icingaweb2-module-director#1894]
Hi!
Cloning scheduled downtime does not work.

## Expected Behavior
Click on clone link and as in case of other director objects a cloning window should be displayed.

## Current Behavior
Clicking on the clone link results in an error message: "Page not found."

## Steps to Reproduce (for bugs)
Create a Scheduled Downtime in Director and then click on the clone link.

## Your Environment

* Director version (System - About): Director-master version from 2019.06.11
* Icinga Web 2 version and modules (System - About): icingaweb2-2.6.1-1.el7
* Icinga 2 version (`icinga2 --version`): icinga2-2.9.1-1.el7
* Operating System and version: Red Hat 7.6
* Webserver, PHP versions: httpd-2.4.6-89.el7_6, rh-php71-1-1.el7

**Comment by dfrise** [comment]
We see same problem with our -newer- environment:

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.8.1
  * enforceddashboard: 0.0.0
  * fileshipper: 1.1.0
  * grafana: 1.3.5
  * incubator: 0.5.0
  * ipl: v0.4.0
  * reactbundle: 0.7.0
* Icinga 2 version (`icinga2 --version`): 2.12.0-1
* Operating System and version: RHEL 7.8
* Webserver, PHP versions: Apache/2.4.6, PHP 7.3.11

We noticed from the logs  that the URL for the clone operation is not the same:
```
[10/Aug/2020:13:23:45 +0200] "GET /icingaweb2/director/scheduled-downtime/edit?name=Cpu-XXXXX HTTP/1.1" 200 8731
[10/Aug/2020:13:23:51 +0200] "GET /icingaweb2/director/scheduledDowntime/clone?name=Cpu-XXXXX HTTP/1.1" 404 719

```
HTH

**Comment by wopfel** [comment]
Hi @dfrise, nice catch!

I've tested this in the standalone vagrant box right now. If I change the URL manually to `http://192.168.33.5/icingaweb2/director/scheduled-downtime/clone?name=test-1` (a dash in scheduled-downtime), the cloning panel appears. Insert a new name, and hit the Clone button. The downtime is successfully cloned, though a "Page not found" panel appears. But if you visit the downtime list in the Icinga Director, you can see that the cloning was successful.

(The page-not-found error is raised because a redirect to `.../scheduled_downtime?name=...` is generated.)

Unfortunately, I didn't find a clue what should be changed after looking in several .php files. 

Maybe someone (@Thomas-Gelf? 😉) can point me to the right files and I'll check if I can create a PR.

Kind regards,
Bernd

**Comment by Thomas-Gelf** [comment]
Hint: scheduled-downtime VS scheduledDowntime VS scheduled_downtime

**Comment by wopfel** [comment]
Thomas, thanks for joining in and giving this hint.

Unfortunately, I wasn't successful. I've changed several php files using various combinations. 

I guess there's some auto-generated link behavior I'm not aware of. For example, the "Apply" button generates a link to .../scheduled_downtimes/applyrules, but I didn't find any "scheduled_downtimes" in the source PHP files.

**Comment by Thomas-Gelf** [comment]
@wopfel: you're right, there is some black magic behind this. Methods involved: `getType()`, `getPluralType()`, they're derived from Object/Table-Names. I'll try to make it more explicit, don't like it either - that should make it easier to understand. Starting from next week I'm finally allowed to dedicate two weeks to the next Director release, I pinned this issue to that milestone.

**Comment by wopfel** [comment]
Thank you, @Thomas-Gelf 😃

**Comment by Thomas-Gelf** [comment]
You're welcome :-)
