### ISSUE TITLE
add hints where to find the checks from external commands

### ISSUE THREAD

**Issue by fireba11** [Icinga/icingaweb2-module-director#1942]
There are quite a few Command pre-defined as external commands, but there is no hint where the plugins for the checks can be aquired. Quite a few come with a normal installation on debian, but others (for example check_elasticsearch) do not.
If you could provide hints where those are from that would be really usefull especially since icinga-exchange/nagios-exchange sometimes got more than one plugin by that name with different syntax :-/

**Comment by idandr** [comment]
External commands (usually) come from the Icinga 2 Template Library (ITL). In the documentation of the ITL are links to the source of each check. For check_elasticsearch see https://icinga.com/docs/icinga2/latest/doc/10-icinga-template-library/#elasticsearch which links to https://github.com/anchor/nagios-plugin-elasticsearch . Hope that helps and addresses your question.

**Comment by Thomas-Gelf** [comment]
I like this feature request. IMHO every external/ITL-Command should be able to point to it's upstream project/source. Currently there is no place for this, but we have inline links in our documentation. Couldn't we provide an optional `website` property for our `Command`-objects?

This would allow us to maintain references to the related plugin in the ITL, and the Director could show related links - where available.

@dnsmichi: what's your opinion on this?

**Comment by fireba11** [comment]
@idandr thank you for pointing me in the right direction :-)
@Thomas-Gelf that sounds like a very userfriendly way to include that information

**Comment by dnsmichi** [comment]
I like the idea. I am only undecided about the actual attribute name, I would rather opt for `plugin_url` or `script_url` or `source_url`. 

Mainly because some plugins are taken from a Git repository with long direct urls, accompanied by others. The majority of the plugins likely points to exchange.icinga.com or single GH repos. 

Event/Notification command objects should also be taken into account. 

Maybe we just call it `docs_url` and always point to the icinga docs, keeping the URLs for the ITL documented in just one place.

**Comment by Thomas-Gelf** [comment]
@fireba11: you might eventually want to open a dedicated issue in the [Icinga 2 issue tracker](https://github.com/Icinga/icinga2/issues) to speed things up. There is nothing we can do here unless this has been implemented. When creating the issue please link this one and eventually ping me once this feature is available. I'll close this issue so far.

Thanks,
Thomas

**Comment by dnsmichi** [comment]
I had this on my TODO list and have talked with @lippserd about it.

- `notes` or `description` would be a good name for this attribute. This could also use heredoc and markdown as string value then.
- Due to the feature freeze with the new IcingaDB backend and as such, no additional attributes for 2.12, we cannot add this anytime soon.

Cheers,
Michael
