### ISSUE TITLE
Director Background Daemon: confusing alarm state

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#2051]
Hi,

Director (using 1.7.2) offers Tabs Overview, Health and Daemon.

Tab "Health" is fine: it reports me `No Import Sources have been defined`, `No Jobs have been defined` and so on. But tab "Daemon" is marked orange:

```
The Icinga Director Background Daemon is not running.
Please check our documentation in case you need step by step instructions showing you how to fix this.
```

But not every setup needs this background daemon. The orange WARNING state suggests: uh, there's something terribly wrong here. But in fact (in this case, at least), it isn't. Have to explain that very often ;)

So this is kind of a feature request (open to discuss) with respect to the user interface: tab "Daemon" is a great idea, but it should not have an initial state as Daemon is not mandatory to use Director.

Cheers,
  Marianne

## Your Environment

* Director version (System - About): 1.7.2
* Icinga Web 2 version and modules (System - About): 2.7.3
* Icinga 2 version (`icinga2 --version`): r2.11.2-1
* Operating System and version: Ubuntu 18
* Webserver, PHP versions: apache2, php7

**Comment by Thomas-Gelf** [comment]
Hi @sysadmama,

you're right, the warning is there to annoy people. This is 100% intentional :laughing:

Upcoming versions will shift more and more tasks to the background daemon. Starting with v1.8 it will be mandatory, and then this orange tab will turn red. Quite some new features will fully depend on a running daemon.

We started to annoy people since v1.7, because:

- upcoming features that will hit the master should just work for those who're running on the bleeding edge
- we want everybody to be ready once v1.8 is there

Getting rid of that alarm state is easy: follow the shown documentation link and enable the daemon. You'll need it anyways.

Cheers,
Thomas

**Comment by sysadmama** [comment]
Hi,

fastest answer award 😳
When you tell me to use this daemon I'll do so of course. I overlooked the word `mandatory` in upgrade instructions, so sorry for the noise.

Cheers,
  Marianne
