### ISSUE TITLE
How to Override automation using director

### ISSUE THREAD

**Issue by GUNALAN952** [Icinga/icingaweb2-module-director#2124]
Hello Team,

We want to onboard PostgreSQL services automatically using icinga director.

Currently we are able to on-board host and single services (and service set) via-director automation process .

We are able to populate host custom property (defined via data fields) automatically and overriding service custom vars manually .

Please suggest us how to automate this using director?

**Comment by Thomas-Gelf** [comment]
@GUNALAN952: you're using Sync Rules to generate single services and you want to use "Variable Overrides" to allow your users to change defaults shipped via Sync. Did I get this right?

If so, please:
* add a Sync Property to your Service Sync Rule
* destination field: `use_var_overrides`
* source column: `Custom expression`
* source expression: `y`

Otherwise please share more details about what you already have and what exactly you want to achieve.

**Comment by GUNALAN952** [comment]
Hi thomas , Yes you got it right 
                 i tried what you mentioned but iam not seeing  use_var_overrides in the destination field 
![WhatsApp Image 2020-05-11 at 9 57 54 PM](https://user-images.githubusercontent.com/54971983/81586003-9296e800-93d2-11ea-8bd0-0ace87c7f4e1.jpeg)

**Comment by GUNALAN952** [comment]
Any thoughts for this one yet?

**Comment by Thomas-Gelf** [comment]
You have to scroll down in this list, if this is a Sync Rule for Services it should be there

**Comment by GUNALAN952** [comment]
thanks @Thomas-Gelf for resolving it

**Comment by harsha692** [comment]
👍
