### ISSUE TITLE
Icinga Director Automation fileshipper

### ISSUE THREAD

**Issue by GUNALAN952** [Icinga/icingaweb2-module-director#2126]
okay

**Comment by Thomas-Gelf** [comment]
First of all: I'd **strongly** advice against doing so. That's not what Service Overrides have been implemented for. They should allow users to override Service Defaults (from Rules or Imports) on Host level. By setting them via Sync you completely break this feature.

If you really want to do this: you have to use the correct variable name, in your case it has to be `_override_servicevars` instead of `"override_servicevars"`.
