### ISSUE TITLE
„Incorrect string value“ when importing non utf8-valid data

### ISSUE THREAD

**Issue by sysadmama** [Icinga/icingaweb2-module-director#2143]
Hi!

Here's the problem: several people are working on a CMDB without any kind of activity log for good reasons. One of them manages it to break the whole Director import by inserting spaces (for example, it could also have been umlauts). And so, the import fails:

```
Hosts from XXX (SQLSTATE[22007]): Invalid datetime format: 1366 Incorrect
string value '\xA0\xA0' for column 'property_value' at row 1, query was: INSERT
INTO imported_property (checksum, property_name, property_value, format)
VALUES (?, ?, ?, ?))
```

As this happens at the import, using modifiers is not an option. But for the people it's a huge problem as they don't know **where** the error is located – they only know that there **is** an error and it's within their CMDB data (which could have thousands of entries).

Perhaps Director should transform to-be-imported-data to valid utf8 first before trying to `INSERT INTO`?

Perhaps it's possible to extend the Director's debugging capabilites at this point so it's possible to determine the entry causing this error?

Perhaps it's possible to show a more user-friendly message?

Using Director master, PHP 7.1.8, Icinga Web 2  2.7.3. But it seems to be [known behaviour](https://github.com/Icinga/icingaweb2-module-director/issues/177).

Cheers,
  Marianne

`ref/NC/681351`

**Comment by Thomas-Gelf** [comment]
Imported data is required to be UTF-8. In case it isn't, there are related property modifiers. Invalid data will cause an error, the whole transaction is rolled back. That's the expected behaviour.

The message raised by the database is misleading, please do not ask me how they come up with "Invalid datetime" for a UTF-8 text column. This should better read "\x... is not a valid character for <whatever> encoding". Could be worth opening an issue in their tracker.

I'd love to improve the message, but I'm unsure whether it is worth to add thousands of extra function calls for everyone else how is able to ship valid data ;-)

Thoughts?

**Comment by Thomas-Gelf** [comment]
Once storing an import fails, data is now recursively checked for invalid UTF-8 characters. If such are found, a dedicated exception with more details is thrown, otherwise the original exception will be forwarded:


![director_utf8-error](https://user-images.githubusercontent.com/553008/87170591-d4101a80-c2d1-11ea-8f0c-a6b4f47b164d.png)
