### ISSUE TITLE
Unique field name not unique

### ISSUE THREAD

**Issue by widhalmt** [Icinga/icingaweb2-module-director#2284]
## Expected Behavior

When defining two fields with the same name Director should refuse creating the second field.

## Current Behavior

![ATT75396 2](https://user-images.githubusercontent.com/504849/107664886-27de4a00-6c8d-11eb-868a-fb348951c951.jpg)

We were able to two fields with the same field name. Trying to delete one of them would remove both of them.

## Possible Solution

Check for existence of field before allowing to create one.

## Steps to Reproduce (for bugs)

* Create a field
* Create a second field with the same field name

## Your Environment

ref/NC/702000

**Comment by Thomas-Gelf** [comment]
Not an issue, this is an essential feature :-)

**Comment by khmuth** [comment]
I don't understand why it should be feature that a unique field can be created multiple times. Since "Label" and "Field Name" are the same, I can't tell which field I'm selecting when I want to use it in a servcie template or command.

**Comment by Thomas-Gelf** [comment]
Hi @khmuth!

Typical use-case:

* Windows users are supposed to lack typewriting capabilities. That's why the get a dropdown element for the **location** field
* Linux users get an auto-completion **location** field. In addition to this, we trust them: in case they add an unknown location, it will automatically extend the location DataList
* Unix users do not need this level of comfort and are usually irritated by next-generation elements like drop-down select boxes. They get a simple plain text input field

Don't take the example too serious, but I think shows the intention behind all this. Over time we added more and more capabilities to the fields themselves, and eventually one way we're able to put such logic in a single field definition. Until then, the possibility to define differing fields for the very same Custom Variables is often very useful. Either for:

* vars on the very same host, but for a different audience
* vars on completely different templates in multi-tenant setups, using overlapping variable names in distinct realities

Hope this helps with better understanding the reasoning behind this feature.

To address your very specific example, deleting one of them does not remove the other one - don't worry. The table shows to fields with the same name, one of them is no longer in use and can safely be deleted. The table shows also that there are 8841 custom variables matching the name of those fields.

Once you click the delete button, it will ask **Also wipe all "DNSDOMAIN" custom variables from 8841 objects?** You have to actively choose **Yes** to do so, otherwise they remain in place. The related field description reads:

> Leaving custom variables in place while removing the related field is perfectly legal and might be a desired operation. This way you can no longer modify related custom variables in the Director GUI, but the variables themselves will stay there and continue to be deployed. When you re-add a field for the same variable later on, everything will continue to work as before

Cheers,
Thomas

**Comment by khmuth** [comment]
Hello @Thomas-Gelf,

thank you very much for the detailed explanation. I understood it through the use cases.

Regards
Karl Heinrich.

**Comment by Thomas-Gelf** [comment]
You're welcome!
