### ISSUE TITLE
Changing check command for single services

### ISSUE THREAD

**Issue by koerb** [Icinga/icingaweb2-module-director#2293]
## Expected Behavior
Possibility to change the check command

## Current Behavior
Need to add a new service

**Comment by Thomas-Gelf** [comment]
This is intentional: you can grant access to single host and service configuration to users with less privileges, and they should not be able to modify properties that can cause any harm. Templates are accessible to admins only and allow you to lock down the setup according your very personal needs.

We know that our concerns in this regard are a non-issue for many environments, that's why we plan to loosen this restriction. Please follow #2191 (and it's counterpart, #2190) for related changes.
