### ISSUE TITLE
Configurable PHP ini setup - MemoryLimit 

### ISSUE THREAD

**Issue by BorisTrnka** [Icinga/icingaweb2-module-director#2299]
Hello,

  I'd like to open a feature request to be able to tweak the PHP ini setup for the Icingaweb2/director module.
  For example to adjust the actual MemoryLimit. This seems to be "hardcoded" in couple files:

> root@:/usr/share/icingaweb2$ grep -r MemoryLimit *
> modules/director/library/Director/Objects/ObjectApplyMatches.php:        MemoryLimit::raiseTo('1024M');
> modules/director/library/Director/Objects/ImportSource.php:        MemoryLimit::raiseTo('1024M');
> modules/director/library/Director/IcingaConfig/IcingaConfig.php:        MemoryLimit::raiseTo('1024M');
> modules/director/library/Director/Cli/Command.php:        MemoryLimit::raiseTo('1024M');
> modules/director/library/Director/Db/MembershipHousekeeping.php:        MemoryLimit::raiseTo('1024M');
> modules/director/library/Director/Import/Sync.php:        MemoryLimit::raiseTo('1024M');

Thanks.

**Comment by Thomas-Gelf** [comment]
Hi @BorisTrnka,

don't worry, they look hard-coded - but they're very soft :rofl:. These are arbitrary limits, just to avoid most issues with systems using low conservative defaults. The logic in `MemoryLimit::raiseTo()` is as follows:

* raise the limit to the given value...
* ...unless there is no limit configured (`memory_limit = -1`)...
* ...and unless the configured limit isn't higher than the requested one

This means that as long as you have a higher limit in your `php.ini`, above values have no effect.

With that many configured objects reaching 1 GB is to be expected. It will currently probably not need that much more, so I'd suggest setting it to 2 GB and give it another try. From personal experience with similar setups I blindly guess that doing so will probably allow you to grow up to twice your current setup size.

Please note that your operating system uses different php.ini files for the CLI and for the web PHP SAPI, you need to adjust both of them. Unlimited (-1) is also an option, but I'd advise against doing so. Artificial limits allow you to detect potential bottlenecks early on.

Best,
Thomas

NB: In case you're wondering, my colleagues pinged me today, pointing to your support issue. That's why I have some rough knowledge about your setup and sizing.

**Comment by BorisTrnka** [comment]
Hi,
  yeah, nothing is written into the stones ... still it's a "soft"ware :)
  Yes, I was advised to try the enhancement request as it may be usable for implementations as ours. 

  Reason: we are migrating Icinga "master" landscape to new location - for simpler, more seamless migration most of the content (files, DB) was copied. Having same OS (Ubuntu18), copied files, DB ... still "one" != "one" ... :(

  Triggering configuration deployment from Director's web UI for original landscape runs well, for new one we get "_ERROR - ErrorException in .../IcingaConfigFile.php:131 with message: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 815104 bytes)_" as a response after 2-3s since the "click".

  Compared php.ini setup -> same values for both locations -> I expect same MemoryLimit::raiseTo(1024M) executed ...
> /etc/php/7.2/apache2/php.ini
> memory_limit = 128M
> 
> /etc/php/7.2/cli/php.ini
> memory_limit = -1

  Raising the value to double (2GB) seems to be a solution (quick test looks promising); so we look for a place to enter quite specific value to be used just for the purpose; not generally. Any advice?

  Thanks.

**Comment by Thomas-Gelf** [comment]
Hi Boris,

the joke was referring to the fact that there is no hard limit in the Director, even if it looks like such. Your php.ini will always win, when you want to grant more than 1 GB. So no need to change the code, just set `memory_limit = 2G` in your `/etc/php/7.2/apache2/php.ini` and it should work just fine.

Cheers,
Thomas

**Comment by BorisTrnka** [comment]
Hi,
  seems miracle solved ... just found the right php.ini with different memory limit set >> 4GB ... explains a lot (that's the reason I removed previous comment).

  Thanks for the zeal. Appreciated.
  
  Closing issue.

**Comment by Thomas-Gelf** [comment]
You're welcome, glad I could help!
