### ISSUE TITLE
Director deployment stuck Pending - service constantly restarting - DB Locked

### ISSUE THREAD

**Issue by dakide** [Icinga/icingaweb2-module-director#2305]
## Expected Behavior
Deploy a config using Director, it gets applied.

## Current Behavior
Deployed a config, and it's now stuck in pending mode.
The icinga-director service keeps getting restarted.
Error in the logs: 
`icingadirector[2855]: RuntimeException in /usr/share/icingaweb2/modules/director/library/Director/Daemon/DaemonDb.php:161 with message: DB is locked by a running daemon instance, will retry`

This is the log of the service:
![image](https://user-images.githubusercontent.com/53129107/112031658-7ce66900-8b33-11eb-8cd9-4ae8087b74eb.png)

## Your Environment
```
icinga2 - The Icinga 2 network monitoring daemon (version: 2.12.3)
System information:
  Platform: CentOS Linux
  Platform version: 8
  Kernel: Linux
  Kernel version: 4.18.0-240.15.1.el8_3.x86_64
  Architecture: x86_64
  
Icinga Web 2  2.8.2
Git Commit    8a89839af94a247ee2149b2336c73b8251b477c0
PHP Version   7.2.24
MODULE       VERSION
cube         1.1.0
director     1.8.0
doc          2.8.2
incubator    0.6.0
ipl          v0.4.0
monitoring   2.8.2
reactbundle  0.7.0
```

**Comment by Thomas-Gelf** [comment]
First: this error happens when either Director has forcefully been stopped (eventually look for this error's first appearance) or when another instance hold's a DB connection. You can verify whether ANY instance is connected in the web front-end (Director -> Daemon tab) or via `systemctl status icinga-director.service`. You'll NOT see a "I'm taking over this DB connection" 10 seconds later, as that message's log level is too low.

However, what we're seeing here is systemd forcefully killing the daemon, as it doesn't seem to react for 30 seconds. So, that's the main problem here. Please stop the daemon and run it in the foreground in debug mode, this should give us more details:

```systemctl stop icinga-director.service
su - icingadirector
icingacli director daemon run --trace --debug
```

You can stop the foreground daemon with `CTRL-C`.

**Comment by dakide** [comment]
Thanks Thomas. 
After stopping the icinga-director service I started it in foreground mode as you suggested.
It still produced that error message - DB is locked - but after a few seconds it was able to connect to the database, and stay connected.
![image](https://user-images.githubusercontent.com/53129107/112144349-026c2680-8bd1-11eb-9f94-b3dffe123de8.png)

My pending deployment was able to finish.

**Comment by dakide** [comment]
However, new deployments fail with this message:
![image](https://user-images.githubusercontent.com/53129107/112145460-4b70aa80-8bd2-11eb-8fb5-5445ba264978.png)

Running the Kickstart importer also fails:
![image](https://user-images.githubusercontent.com/53129107/112145512-5fb4a780-8bd2-11eb-80e9-d9c0b6c381f1.png)

I'm not sure what is timing out exactly.

**Comment by Thomas-Gelf** [comment]
The first part (on CLI) works as expected, the green messages are usually not shown in the normal log. You might want to add `--verbose` in the unit file to see those. We'll address this with #2235. Did the daemon successfully collect the last deployments? The last two screenshots are showing that the web front-end isn't able to connect to your Icinga Daemon. Is the process running? Can you connect to the host/port used by the Kickstart form? What does `systemctl status icinga2.service` say? Has this ever been running, or is this a completely new setup?

**Comment by dakide** [comment]
> Did the daemon successfully collect the last deployments?

I'm not sure what you mean by collect. When the daemon was stuck in the restart loop, the deployment was pending. 
When the daemon became stable, the deployment finished (it failed, but that was due to a wrong config change)

> Can you connect to the host/port used by the Kickstart form? 

The port is open on the host (same host), and I'm able to connect to it:
![image](https://user-images.githubusercontent.com/53129107/112198377-f0a47680-8c04-11eb-9422-f60fda9bb180.png)


> What does systemctl status icinga2.service say?

It's running fine, I haven't had issues with that side:
![image](https://user-images.githubusercontent.com/53129107/112197924-7f64c380-8c04-11eb-80bf-50f6505a7664.png)

> Has this ever been running, or is this a completely new setup?

Not a new deployment. This was running fine, and deployments running fine, until December 2020. Then something crashed, and there was a Deployment pending since then, not able to run new deployments after that. Now I'm tasked with resolving this.

**Comment by Thomas-Gelf** [comment]
> > Did the daemon successfully collect the last deployments?
> 
> I'm not sure what you mean by collect. When the daemon was stuck in the restart loop, the deployment was pending.
> When the daemon became stable, the deployment finished (it failed, but that was due to a wrong config change)

Deployment consists of multiple steps:

* Configuration is rendered
* Rendered configuration is submitted to Icinga (now it is shown as pending in the deployment list)
* Icinga forks a new process that tries to load the new configuration
* Director collects state and startup log of that operation

The first two steps can be accomplished in the UI or by the daemon (via an automated Job), the last step is (since v1.8) always being executed by the daemon.

> The port is open on the host (same host), and I'm able to connect to it

The reason I asked for was that your screenshots showed that it wasn't able to reach the core. Might be a problem, might have been a short period during a deployment / Icinga restart

In case the problem persists please stop the daemon via systemd and keep it running in the foreground (like you did before). Go to your deployments, are some of them still pending? How many of them? Is your configuration small or large? Please also share a screenshot of your Daemon status page (once while running via systemd, once while running manually) and the output of `grep -rH memory_limit /etc/php`

Finally, while still running the daemon (with debug and trace) in the foreground, please deploy a new configuration. What happens?

**Comment by dakide** [comment]
Hi Thomas,

> Go to your deployments, are some of them still pending? How many of them?

No pending deployments, but there are 60 pending changes, which are ready to be rolled into a deployment.

>Is your configuration small or large?

I'd say it's small to medium. There are 4 import jobs managing a few hundred hosts.

This is the Daemon status page:
![image](https://user-images.githubusercontent.com/53129107/112320776-3d408e00-8ca7-11eb-8408-5aa2d395e795.png)

When I click on the Deploy changes button, I get the same error:
![image](https://user-images.githubusercontent.com/53129107/112320860-547f7b80-8ca7-11eb-9576-61ffdc1c8785.png)

And there are no logs written to the terminal:
![image](https://user-images.githubusercontent.com/53129107/112320961-695c0f00-8ca7-11eb-89aa-9acf2a33b04e.png)

When I make a change and go to deploy it, I get the same error message as above, and nothing written to the terminal.

The PHP memory_limit is 128MB
`/etc/php.ini:memory_limit = 128M`

**Comment by Thomas-Gelf** [comment]
Does the deployment take place when you launch it? The red error shows that your web instance isn't able to talk with Icinga. In case SElinux is active you might eventually want to check the related [documentation](https://icinga.com/docs/icinga-2/latest/doc/22-selinux/), check httpd_can_connect_icinga2_api or similar.

Regarding the daemon: please do not run it as root. You can switch the user as follows:

```
su - icingadirector -s /bin/bash
icingacli director daemon run --trace --debug
```

And please remove `--verbose`, as it overrides `--debug` in that case - and debug has more details. The `memory_limit` is probably not related to your problem, otherwise it would have popped up somewhere. A few hundred hosts shouldn't be a problem, but I would nonetheless raise it to `256 MB` - just to be on the safe side. 128 is pretty conservative.

You might want to `tail -f /var/log/audit/audit.log` while trying to deploy, in case SElinux is involved it should be logged. Your web servers error log might also have some hints.

**Comment by dakide** [comment]
>Does the deployment take place when you launch it? The red error shows that your web instance isn't able to talk with Icinga

Nope, it errors out and the 61 pending changes are still pending, deployment doesn't start.
SELinux is off, nothing written to `audit.log`

Increased the memory limit to 256, restarted apache and icinga2, and I'm running the daemon without verbose.
Deployment fails with the same error, and the Kickstart also fails with the same error as the original ticket.
![image](https://user-images.githubusercontent.com/53129107/112327766-9dd2c980-8cad-11eb-8ef1-2c517c5ff56b.png)

![image](https://user-images.githubusercontent.com/53129107/112327410-51878980-8cad-11eb-8997-55f32e927a1d.png)

It's strange there is a disconnect between the Director and Icinga.
Could it be an Endpoint mis-configuration? 
Would it be easier at this point to start from fresh? A brand new install and I will just have to put in the time to re-create the configuration.

**Comment by Thomas-Gelf** [comment]
Endpoint misconfiguration could be an explanation, especially as you explicitly mentioned Kickstart ;-) What was your motivation to go there initially? Please check the settings in that form, and check the related Endpoint on your Icinga Config Master. The `host`-Property must match the IP (or hostname) the Web is talking to. If that doesn't succeed it should be fixed first

**Comment by dakide** [comment]
Wow this is embarrassing - I added the endpoint hostname into the hosts file and it all seemed to work.
![image](https://user-images.githubusercontent.com/53129107/112333616-ac6faf80-8cb2-11eb-982e-baca59dfdf65.png)

Sorry for the trouble and thank you Thomas for your help!

**Comment by Thomas-Gelf** [comment]
Guess either the host name, the name resolution or the Endpoint configuration has been touched at some point in time. You're welcome, glad I could help.
