### ISSUE TITLE
Supporting inline DSL

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#2324]
I'm working on a project requiring special check_period and notification_period for Hosts.

The idea is to have hosts that are only available during a specific time of day, and checks and notifications shall be disabled beyond those times.

The goal is to avoid creating too much notification and service specific objects, when the value for those periods can be referenced. The mass of objects should only come from `TimePeriod` objects and just used on a host or host template.

## Just Icinga 2

In just Icinga 2 DSL this is pretty easy:

```
object Host "branch-1234-router" {
  import "default host"
  address = "127.0.0.1"

  check_period = "branch-1234"
}

template Service "branch-service" {
  import "default service"

  // This will require host handling similar to DirectorOverrideTemplate for non-apply services
  if (host.check_period) {
    check_period = host.check_period
  }
}

apply Notification "branch-service" to Service {
    command = "some-notification"

    users = ["branch-admins"]

    if (service.check_period) {
        period = service.check_period
    } else if (host.check_period) {
        period = host.check_period
    }

    assign where host.vars.branch
}
```

## Director

I thought about building a specific handling for periods to support this, but it might be finally time to implement DSL support with a input to host and service templates.

The idea would be to add new inputs to the template forms, and render an inputted DSL snippet to the end of the object config. So admins could introduce custom behavior.

It could be an optional feature that needs to be enabled.

I would take care about the implementation for a customer project.

Thoughts @Thomas-Gelf
cc @tredel @mwaldmueller @lippserd 

ref/NC/706238

**Comment by Thomas-Gelf** [comment]
Hi @lazyfrosch,

before investing too much effort into this, please consider that allowing raw DSL in any template is a no-go. This was one of our main premises when building Director at first. It breaks essential features that where hypothetical but foreseeable once we drafted this project, which are a reality now, and which are currently becoming more important with every release.

> The Director MUST be able to fully resolve all objects, this is especially important for Apply Rules defined with the Director

Command Definitions are exempt from this rule, as they are not directly relevant for any UI operation (like "Modify Service") and not relevant for eventual User Restrictions. This becomes impossible as soon as you allow for DSL in any Host or Service, same goes for Host or Service Vars. To make a simple example, fitting the ones above: imagine someone adding `ignore where service.check_period = "whatever"` to a Service Template used in an Apply Rule. This service would appear where it does not belong to.

I understand that adding a very few form fields and preparing related DB migrations is a trivial task, and therefore looks promising. But the issues deriving from this would bind resources for years to come - and that's why I strongly oppose doing so. Your requirements can easily be solved as of today, without changing a single line of code. Please have a look at the example shown in ref/NC/723118.

In addition to this, count me in for the following related feature ideas:

* implement `external_object` for more object types to skip the "disabled-template" step
* integrate the fileshipper, add File Drop functionality and an optional "large text area"
* ship a set of well-defined and -named DSL-hacks for specific use-cases with related UI functionality _(not trivial, as they MUST always come with related modifications for our Resolver classes. Those are currently not extensible, that's tricky. Related Hooks might be provided once we got some experience with such extensions)_

Hope this helps!

Cheers,
Thomas

**Comment by lazyfrosch** [comment]
Very interesting, going to document this here and maybe with the documentation of fileshipper as a use-case.

**Comment by lazyfrosch** [comment]
I'm going to solve this with fileshipping:
https://github.com/Icinga/icingaweb2-module-fileshipper/blob/master/doc/04-FileShipping.md

A good example can be found here:
https://github.com/NETWAYS/icinga2-examples/blob/main/fileshipper-templates/README.md
