### ISSUE TITLE
[dev.icinga.com #11840] Add set_if macros as field is not possible

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#250]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11840

**Created by Benedikt1992 on 2016-05-25 08:32:33 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _1.3.1_
Last Update: _2016-11-30 08:36:58 +00:00 (in Redmine)_

---

It is not possible to choose a macro as field when it is added as "Condition (set\_if)" in a command. E.g. the built in command by\_ssh:

object CheckCommand "by\_ssh" {
execute = PluginCheck
command = \[ PluginDir + "/check\_by\_ssh" \]
timeout = 1m
arguments = {
"-C" = "$by\_ssh\_command$"
"-H" = "$by\_ssh\_address$"
"-c" = "$by\_ssh\_crit$"
"-i" = "$by\_ssh\_identity$"
"-l" = "$by\_ssh\_logname$"
"-o" = {
"description" = "Provide ssh options (may be repeated)"
"value" = "$by\_ssh\_options$"
}
"-p" = "$by\_ssh\_port$"
"-q" = {
"set\_if" = "$by\_ssh\_quiet$"
}
"-t" = "$by\_ssh\_timeout$"
"-w" = "$by\_ssh\_warn$"
}
vars.by\_ssh\_address = "$check\_address$"
vars.by\_ssh\_quiet = false
vars.check\_address = {
"type" = "Function"
}
vars.check\_ipv4 = false
vars.check\_ipv6 = false
}

It is not possible to set the $by\_ssh\_quiet$ via a field

**Comment by Thomas-Gelf** [comment]
Hint: the data type issue should have been fixed quite some time ago. Macro is still not suggested, that's the remaining issue. Workaround (manually create a field) exists.

**Comment by mwaldmueller** [comment]
+1

**Comment by takeda** [comment]
Will this ever be implemented? The ticket was opened year and half ago, and the issue causes problems when using some commands that are included with icinga2 (disk (specifying -A), load (enabling per CPU calculation) etc)

**Comment by Thomas-Gelf** [comment]
@takeda: it's currently not scheduled. Adding fields "as suggested" is currently only able to add string fields, for set_if you usually want to have Booleans. So, please go to your Director Dashboard, Data Fields, create a corresponding field, go back to the Command, assign the field.

It's a few clicks more for now, shouldn't be required that often. Sooner or later we'll fix this. It might sound simple, but it will cost quite some time.

**Comment by PaulSzymanski** [comment]
+1

**Comment by Bitblade** [comment]
Please note that the workaround indeed isn't much extra work. However, finding the workaround is. 

As an Icinga / Director beginner, I've been searching on and off for almost a week (and indeed given up once or twice) for a solution to the problem why the http_sni and http_ssl fields don't show up.

I was about to open an issue because I couldn't find anything about this problem. When doing research in order to create a useful issue, I finally started to understand what was going on and found this issue by searching for "set_if" and reading through two pages of issues. 

To do this, I needed to: 
1. Know that the check commands are imported into Director by the Kickstart process (although the web ui refers to "the Core API").
2. Know that to import them, the kickstart process looks for a file that defines the arguments to each check command.
3. Realise that the import process is a likely culprit.
4. Realise that it's mostly the boolean fields that are missing
5. Know that arguments to check commands can be defined in the aforementioned files with "value" or "set_if" macro, where set_if is used for booleans

I would suggest adding a warning or note to the web UI.

**Comment by Thomas-Gelf** [comment]
DSL is allowed in Command Definitions and will not be a thing in Fields for now.
