### ISSUE TITLE
Changed Debian package name - migration needed?

### ISSUE THREAD

**Issue by Stefomat** [Icinga/icingaweb2-module-director#2637]
Hello there,

i have the following issue.

I installed the Icingaweb2 Director via the icingaweb2-module-director package from the extras repo at https://packages.netways.de/, also including the needed dependency for icingaweb2-module-incubator.
Everything was fine, until GitHub notified me about the new release v1.10.1. On my system, apt did not notify about any update, so i investigated.
I found out that the package icingaweb2-module-direcor didn't get the update, but there is a new package called icinga-director over at the official repo (packages.icinga.com).

Now to my questions.
Is it planned that all users currently running icingaweb2-module-director switch to the new package icinga-director?
How does the new package differ from the old one? Any significant changes that can break an existing installation?
Will there be an anouncment, when users are supposed to change packages? If i hadn't received the notification from GitHub, i wouldn't have known about the new release.

Thanks for Icinga and all your work.
Greetings
Stefomat

**Comment by lippserd** [comment]
Hi @Stefomat,

> Is it planned that all users currently running icingaweb2-module-director switch to the new package icinga-director?

Yes.

> How does the new package differ from the old one?

Doesn't differ that much since it also installs Icinga Director 🤣. But it's provided directly by us.

> Any significant changes that can break an existing installation?

Nope.

> Will there be an anouncment, when users are supposed to change packages?

We announced that we now provide packages for Director. NETWAYS provides a transition [1] from their packages to our packages until they are eventually removed.

All the best,
Eric

[1] For new releases that we provide packages for, NETWAYS packages simply install our packages.
