### ISSUE TITLE
[dev.icinga.com #11984] Filter view for manually created/synced commands

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#293]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/11984

**Created by friesoft on 2016-06-17 21:14:12 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-06-17 22:54:44 +00:00 (in Redmine)_

---

Currently there's a huge list of builtin commands (all monitoring plugins) which is nice - but often not needed.

Most checks we need are custom built or check\_by\_ssh. So those we created manually are somewhere in this big list and always have to be searched for.

It would be great if the list could be filtered for those manually created vs. those builtin.

**Comment by Thomas-Gelf** [comment]
In case you removed them from your icinga2.conf please trigger a kickstart run again, then they should vanish. Kickstart URL used to be a hidden feature, but is prominently linked from the new Infrastructure Dashboard since v1.3.0.

To filter them in the list please filter for object_type -> object, but I agree - this should be a single-click operation, or we could also separate them by default.

**Comment by Thomas-Gelf** [comment]
Has been implemented for v1.4.0
