### ISSUE TITLE
Modifying serviceset service throw Ramsey\Uuid\Uuid::fromBytes(): Argument #1 ($bytes) must be of type string, resource given

### ISSUE THREAD

**Issue by Meister1900** [Icinga/icingaweb2-module-director#2934]
## Expected Behavior
There should be no PHP exception when  modifying a service that belongs to a serviceset.

## Current Behavior
Ramsey\Uuid\Uuid::fromBytes(): **Argument # 1 ($bytes) must be of type string, resource given**, called in /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Lookup/ServiceSetServiceInfo.php on line 77

`#0 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Lookup/ServiceSetServiceInfo.php(77): Ramsey\Uuid\Uuid::fromBytes()
#1 /usr/share/icingaweb2/modules/director/library/Director/DirectorObject/Lookup/ServiceFinder.php(49): Icinga\Module\Director\DirectorObject\Lookup\ServiceSetServiceInfo::find()
#2 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(146): Icinga\Module\Director\DirectorObject\Lookup\ServiceFinder::find()
#3 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\HostController->findserviceAction()
#4 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#5 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#6 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#7 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#8 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#9 {main}`

## Steps to Reproduce (for bugs)
Use PostgreSQL DB resource. Create a service set with some checks. Assign it to a host template. Deploy.
Open one of the services in Icinga DB Web. Click "Actions" - "modify"

## Your Environment
* Director version (System - About): 1.11.2 (it was also in previous versions)
* Icinga Web 2 version and modules (System - About): 2.12.2
* Icinga 2 version (`icinga2 --version`): r2.14.3-1
* Operating System and version: Ubuntu 24
* Webserver, PHP versions: PHP 8.3.6

**Comment by Meister1900** [comment]
It's not yet fixed in our environment. Now I get:

**No such object available**
`#0 /usr/share/icingaweb2/modules/director/library/Director/Data/Db/DbObject.php(1324): Icinga\Module\Director\Db\Branch\UuidLookup::requireUuidForKey()
#1 /usr/share/icingaweb2/modules/director/application/controllers/HostController.php(533): Icinga\Module\Director\Data\Db\DbObject::load()
#2 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Action.php(516): Icinga\Module\Director\Controllers\HostController->servicesetserviceAction()
#3 /usr/share/php/Icinga/Web/Controller/Dispatcher.php(76): Zend_Controller_Action->dispatch()
#4 /usr/share/icinga-php/vendor/vendor/shardj/zf1-future/library/Zend/Controller/Front.php(954): Icinga\Web\Controller\Dispatcher->dispatch()
#5 /usr/share/php/Icinga/Application/Web.php(294): Zend_Controller_Front->dispatch()
#6 /usr/share/php/Icinga/Application/webrouter.php(105): Icinga\Application\Web->dispatch()
#7 /usr/share/icingaweb2/public/index.php(4): require_once(String)
#8 {main}`

**Comment by lippserd** [comment]
@raviks789 Can you please have another look?

**Comment by raviks789** [comment]
@lippserd, this does happen in Postgres. But this could be considered a different issue.

As this depends on how the rows are returned from the database. Since, there are multiple entries in the database for the same service set, one when the service set is created (object_type='template') and other entries when it is associated with hosts (object_type='object'). 

The services under the service set is linked to the entry with object_type='template'. Now when the service looks for the service set, it is only searching by its name and hence multiple rows are returned and the first row from these rows is selected.

In case of MySQL it is not an issue as the ordering is done in according to the primary key, hence it always selects the service set entry which is linked to the service. But in case of Postgres it is random, hence it sometimes selects the correct entry and most of the times the entries which are not linked to the service. Hence, you get this error.

Unfortunately, when I tested the fix it had selected the correct row. Hence, I had miss this error.

@Meister1900, thanks for reporting. Could you open a new issue for this?
