### ISSUE TITLE
Data Type "Dictionary" to allow for nested variables

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#337]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12093

**Created by lebvanih on 2016-07-04 11:05:38 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-08-10 19:27:13 +00:00 (in Redmine)_

---

Hello,

We are currently trying to import our running configuration in Icinga Director (1.1.0). Our configuration rely on dictionaries and "nested variables" in our hosts. These are used in our "apply for" rules.
The issue is, that as from what we saw (I checked on this tracker and in the example), there is at the moment no options to reflect this kind of configuration in Director. The example provided in the documentation of Director only refer to Array.

Our configuration is mostly based on the following example from the official documentation (see \[\[http://docs.icinga.org/icinga2/latest/doc/module/icinga2/toc\#!/icinga2/latest/doc/module/icinga2/chapter/monitoring-basics#using-apply-for-custom-attribute-override\]\]):

    vars.interfaces["GigabitEthernet0/2"] = {
         iftraffic_units = "g"
         iftraffic_community = IftrafficSnmpCommunity
         iftraffic_bandwidth = 1
         vlan = "internal"
         qos = "disabled"
      }

We also use this kind of structure:

    vars.an_ncpa = {
        token = "secret"
        load = { warning=10, critical=20 }
        cpuload = { warning=80, critical=85 }
        disk["/"] = { disk_warning="15%", disk_critical="10%" }
        disk["/home"] = { disk_warning="15%", disk_critical="10%" }
      }

The structure above was used for three reasons in our configuration:

1.  Easy to ready (for us at least)
2.  No need to prefix all variable
3.  Valid with Apply For.

I tried to workaround with a data field named like this: "an\_ncpa.token", but it get renamed to "an\_npcatoken" as soon as the configuration is rendered.
Is there any plan to allow dictionary creation in Icinga Director and same question for the "nested variable" (dictionary inside a dictionary for example) ?

If this kind of data structure is not "valid" could you please guide us on what we should use instead?

**Attachments**

* [filter_form_playground.png](https://dev.icinga.com/attachments/download/3563/filter_form_playground.png) tgelf - _2016-08-09 14:57:19 +00:00_

---

**Relations**:

* blocks [#11849](https://dev.icinga.com/issues/11849)

**Comment by cbnorman** [comment]
when is this feature likely to be made available?

**Comment by cschneemann** [comment]
Still working on this? It would be great to have dictionary-support in director

**Comment by tobiias123** [comment]
I'am currently writing my bachelor thesis about the Icinga Director. One point of this is to analyze how to migrate an existing configuration to the Director. There I ran into the issue with the dictionary-support. So are there any news about this? Is there a workaround or something?

**Comment by likg** [comment]
Propose to add an ability to insert user-defined functions also. Icinga2 core supports complex data types since 2015 ([new-features-in-icinga-2-3](https://www.icinga.com/2015/01/13/new-features-in-icinga-2-3/)) and the following vars definition is perfectly valid in Icinga2 world:

```
vars.http_vhosts["icinga.org"] = {
    http_address = "icinga.org"
    interval = 1m
  }
```

```
vars.dummy_text = {{ return "Dummy text here" }}
vars.dummy_state = {{ return 0 }}
```
Director object inspection already represents functions as:
```
vars: {
        dummy_state: { type: "Function" },
        dummy_text: { type: "Function" }
      }
```
Therefore [comment](https://github.com/Icinga/icingaweb2-module-director/issues/337#issuecomment-273105060) sound reasonable to me.

**Comment by friesoft** [comment]
Any news on dictionaries? :-) We are really missing them...

**Comment by marcelfischer** [comment]
We need them too.
For example for filesystem monitoring we have a standard set of filesystems. But we want to change thresholds for a single filesystem for a single or group of hosts.

Currently we have an service set with the defaults and then create a new service set for each exception

**Comment by dnsmichi** [comment]
https://monitoring-portal.org/index.php?thread/42106-puppetdb-import-fehlende-definition-von-endpoint-zone-von-einigen-hosts/&postID=257299#post257299

**Comment by linuxmail** [comment]
Hello,

I wanted to migrate too and stuck now again, after I remembered, why I did not move month ago to the Director module: I need the dictonary support. I have a bigger Ceph storage with many disks (and types) and a lot of switches. For example on some I have SSDs, HDDs, Raid and virtual disks which which can be present as /dev/sda ... I have no idea, how can I solve it without the dictionary type.
The same problem I have for switch ports: from virtual, over standard 1Gbit/s to 100Gb/s ports. So a default array won't work.

Is there workaround for that problem, without moving the whole node to icinga2 conf.d/ again?

cu denny

**Comment by freddy4711** [comment]
+1 for that. It would be a really nice feature, if Director supports Dictionaries. This would make life easier.

**Comment by SimonHoenscheid** [comment]
Any News? @Thomas-Gelf

**Comment by wols** [comment]
Is this a blocker for own function icinga/icinga2#5870 also?

**Comment by mkayontour** [comment]
I do need that too, when working with the command "by_ssh" the by_ssh_arguments variable won't work because it expects a dictionary.

**Comment by CobbleCity** [comment]
+1

**Comment by 3it-n** [comment]
+1

**Comment by phil-or** [comment]
+1

**Comment by rojobull** [comment]
+1. Need dictionary data type fields in Director.

**Comment by lokidaibel** [comment]
+1 Realy needed. Would make so much so more easy,

**Comment by lokidaibel** [comment]
Hey Thomas,

Nexted vars helps alot when you work with other Systems that provide Data for the Monitoring.
For example our use case is the following:

To manage our systems we use Jira. We have workflows in Jira for order a host. Also this workflow "lives" as long the Server is in use. 

Cause we have all the data of the Servers in Jira we created the subtask Monitoring. In this we have a field where our stuff can write JSON like:

URL Checks in the notation: 

"URL_<TEAM>" : "<URL><PORT><Respons>","<URL2><PORT2><Respons2>"

We are applying some rules inside the Director DB to make a loop over all this entry which creates a check like this:

APP_URL <URL><PORT><Respons>
APP_URL2 <URL2><PORT2><Respons2>

The problem is that it will publish all check relevant Data to the public (all users that are able to see the service).

But now we also want SNMP Checks to be applyed that way.
But in this case there will be <OID>,<warn>, <crit>, <pretty_name> which will be a realy long Check name. So i want access only the <pretty_name> for the checks but all i have is $config$ which result in the whole vars displayed.

I dont see how can i accomplish this without nested Vars. But maybe i am doing it wrong as you mentioned

Greetings 

Lukas Matecki from Cologne

p.s. I still own you  some Gin for the next OSMC. Have found some special here in Cologne. Will bring it with me for this year osmc ;-)

**Comment by d-stevens** [comment]
I don't see any way to deploy Service Apply Rules with individual parameters without nested vars or dictionaries.
Simplest example for that is to check a drive usage, but want to change some theesholds on only one drive or host. Since apply-rules only know one $config$ var it is impossible to declare. So I Have to create one check per drive for all hosts. That's not what apply-rules focus on.
By the way: Using a nested var for the display field helps a lot instead of showing the whole data field.

There are some many usecases that can't be deployed without dictionaries.
WE NEED THIS FEATURE!

**Comment by rojobull** [comment]
The way I accomplished this was not by using apply rules. I created a service template that takes in the partition name, and desired thresholds and then applied one service for each partition for each system. Thomas-Gelf's comment above describes doing exactly this.

**Comment by d-stevens** [comment]
But as you said:

> applied one service for each partition for each system. 

This is very time-consuming and cannot handle imports from Inventory scanning, CMDB or something else.
Icinga can do this. It is only the director addon that doesn't.

**Comment by rojobull** [comment]
Even if you use dictionaries, you have to have some way of determining what partitions need to be monitored on each system. If you know this ahead of time, then you can just apply one service for each partition to a host template and you're done. If it needs to be dynamic, as in my case, you need to do something else to determine what partitions each system has. 
We did this outside of Icinga/Director. We wrote a python script enforced by Puppet that each host runs a few times per day, detects its partitions and if there are changes, it adds/removes partitions via the Director API. This way it is automated and we don't have to ever worry about manually adding/removing partitions to be monitored. Also, since Director is in place, we still have a point and click interface where we can adjust thresholds on a per system, per partition basis.

**Comment by d-stevens** [comment]
ok. I understand. what the director cannot do your third-party tool can.
I wanted to import those informations with sync-rules instead of writing an API-Script that does it.
I think it would be more time-saving to write all the configuration in the config-files and use the abillities of icinga2 then using the director + writing api-scripts. And all that only because dictionaries are not available.

**Comment by rojobull** [comment]
You can still use dictionary variables so long as you define the service and apply rules in Icinga2, outside of Director. It just means that you won't be able to manage that particular service and associated thresholds in Director which is not ideal.
I only briefly tested sync'ing and sync rules. In my case I was importing systems from LDAP. It worked great except I didn't see a way to automatically detect each system's partitions. Perhaps there is a way to do it but we just decided to add that logic outside of Director.

**Comment by ss6s** [comment]
WE NEED THIS FEATURE! + 1

**Comment by Gianlu** [comment]
It would be very nice to have this feature.

**Comment by kwiksand** [comment]
Trying to port my manually generated code to  director for "ease" of reuse , but this really seems to be a showstopper.  Any movement on this as a feature?

**Comment by msokolich-ta** [comment]
Like many others here this is a pretty necessary feature for our environment.

**Comment by shake-spear** [comment]
yes - this feature would be quite a scream +1

**Comment by drallgood** [comment]
What happened to this?

**Comment by lokidaibel** [comment]
Hey, it only took 5 Years to get you on our side ;D
Well, constant dripping wears away the stone .

**Comment by Thomas-Gelf** [comment]
Honestly, I'm still not on your side :rofl: In my believes working this way is an ugly hack and leads to redundancy. But now there is no way back, Pandora's box is wide open :scream: And sure, it is a nice feature that helps getting things done.

Reason for this getting implemented was a customer project where the main task was to ship structured data to a bunch of custom-made plugins, where the "real" multi-instance-logic was in those plugins - and partly in their related notification scripts. So they sponsored a few days, allowing me to work on this.

Some related features will follow very soon, stay tuned ;-) There will be some adjustments related to `apply for` rules, and related "Overrides" are a (tricky) topic.

API, CLI and Sync already allowed for structured data, that part continues to work the way it did. With the difference that you can now allow your users to work with that data in the UI too.

**Comment by lokidaibel** [comment]
Though something like that. But i like that you actually closed a issue from over 5 Years ago !
Even you belives are different, hell yeah thats professionalism !
Thx for the fix ! 
Stay healthy, you are the best !

**Comment by Thomas-Gelf** [comment]
Dry-aged issues get better over time :rofl: You're welcome, glad that you like it.

>  Stay healthy, you are the best !

You too! Got Corona-positive in November, no plans to catch it again anytime soon ;-)

**Comment by joni1993** [comment]
I'm really heaving a hard time getting this to work. No matter how i set it up i always run in some kind of exception (either SQL error, or PHP exception 😕 ) - Do you prefer this issue to report or should i create a new one?

**Comment by dskachan** [comment]
> 
> 
> I'm really heaving a hard time getting this to work. No matter how i set it up i always run in some kind of exception (either SQL fetch issues or PHP exceptions 😕 ) - Do you prefer this issue to report or should i create a new one?

confirm. Master is unusable at the moment.

**Comment by Thomas-Gelf** [comment]
Could you please open a dedicated issue, showing the errors/exceptions you're facing?

**Comment by MarcusCaepio** [comment]
Hi @Thomas-Gelf 
I am currently looking at the director again and try to "translate" my DSL config to it.
Although with the new dictionary type, I am not able to translate it 1:1. You said, using dictionaries is a redundancy. So I guess, I am doing sth. wrong. Could you please tell me, how I have to configure the director to get the same result as in this DSL snip? Thanks a lot

```
apply Service "tcp: " for ( tcp => config in host.vars.tcp ) {
  import "generic-service"
  check_command = "tcp"
  vars += config
  assign where host.vars.tcp
}
object Host "abc" {
  [...]
  vars.tcp["123"] = {
    tcp_address = "xxx.xxx.xxx.xxx"
    tcp_port = "123"
  }
  vars.tcp["456"] = {
    tcp_address = "xxx.xxx.xxx.xxx"
    tcp_port = "567"
  }
}
```

**Comment by joni1993** [comment]
As if today i was able to create the dict for a host successfully - IcingaDirector successfully creates a host looking like this:
```
object Host "XXX" {
[...]
    vars.host_interfaces = {
        wan = {
            host_address_ip = "XXX.XXX.XXX.XXX"
            host_address_type = "wan"
        }
        vlan_surveillance = {
            host_address_ip = "YYY.YYY.YYY.YYY"
            host_address_type = "vpn"
        }
    }
}
```

Sadly you cant create a service apply for dict type in director, but manual config works: 
```
apply Service "if-" for (interface_name => interface_config in host.vars.host_interfaces) {
        import "generic-service"

        check_command = "ping4"
        display_name = "Ping [" + interface_name + "]"

        vars.ping_address = interface_config["host_address_ip"]
}
```

**Comment by MarcusCaepio** [comment]
Coming back to this issue, as I am (again) having a look to the new director version. 
@joni1993 I did your patch and can see the dictionary in the host overview. I also can create a new instance, but I am not able to set the properties. Tried to solve my example at https://github.com/Icinga/icingaweb2-module-director/issues/337#issuecomment-878155228 and failed again :( 
I really would like to use the director for automation stuff, but using host dictionaries is a must have for me...
