### ISSUE TITLE
[dev.icinga.com #12271] Setting "imports" for Hostgroup Sync Rules fails

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#384]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12271

**Created by tgelf on 2016-08-01 09:40:50 +00:00**

Assignee: _(none)_
Status: _Rejected_  (closed on _2016-11-02 16:53:06 +00:00_)
Target Version: _(none)_
Last Update: _2016-11-02 16:53:06 +00:00 (in Redmine)_

---

We should either remove the setting as it rarely makes any sense or provide the required lookup method.

**Comment by leeclemens** [comment]
I think this should be implemented.

The use case I have, while there may be a better approach, is that I do not want all Host Groups in a global zone (which is where Director seems to put them).

With the ability to import them, I can place them in the correct zone (file configs) and Import them into Director so that they can be referenced on Templates managed in Director.
