### ISSUE TITLE
[dev.icinga.com #12737] Multi-Customer Support

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#458]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12737

**Created by twidhalm on 2016-09-16 14:02:36 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-11 14:56:57 +00:00 (in Redmine)_

---

Hi,

A customer of mine wants to open their Director installation to some of their customers. They need to make sure that apply rules and other objects only affect their own objects.

Ideas:

-   Add silently a variable like "customer" to every object and add silently `) && host.vars.customer ==...` to every apply rule
-   Add prefixes to every object name and reference like `acme-` so a customer can't use e.g. `host_name` in service definitions to affect hosts of other customers.

This might need additions to Icinga Web 2 to obfuscate those new settings for a customer but to me personally it would be perfectly ok to view them in Icinga Web 2.

Cheers,
Thomas

**Comment by neubi4** [comment]
Hi,

are there any news on the permission system? We would like to create a multi tenant icinga2 system where each team/customer can configure hosts and services on their icinga2 satellites via director.

If there are no news/timeplan on these features, is there a plan or a specification how it should look like? If yes, eventually we can help you realizing this feature.

**Comment by friesoft** [comment]
We are also interested in a multi tenant icinga2 system, also with the usecase of teams doing their configuration in icinga director (like @neubi4 )
Any news on this?

**Comment by Thomas-Gelf** [comment]
I'll close this issue, using Director for multiple teams works fine since [v1.4.0](https://www.icinga.com/2017/10/09/icinga-director-v1-4-0-has-been-released/) and is heavily being used in production. You need to base your restrictions on Host Groups. But as this also works flawlessly with those Host Groups being apply rules based on complex filters, you should be more than covered. Commands and Templates remain admin-only, as there is no way to protect you from someone able to roll out his own commands.

More fine-grained permissions might be added in future. In case you miss something please open a dedicated issue describing your exact use-case with a concrete example.

Cheers,
Thomas
