### ISSUE TITLE
[dev.icinga.com #12777] Allow notifications to pick user(groups) from host/service vars

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#462]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12777

**Created by tgelf on 2016-09-23 14:45:20 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-09-23 14:45:20 +00:00 (in Redmine)_

---

As we are now able to fill custom arrays with Icinga object name through the DirectorObject data type, I'd love to be able to define the following directly through the Director:

    apply Notification "Send Mails for Hosts to their contact groups" to Host {
      import "mail-host-notification"
      user_groups = host.vars.contact_groups
      assign where host.vars.contact_groups
    }

    apply Notification "Send Mails for Services to their contact groups" to Service {
      import "mail-service-notification"
      user_groups = service.vars.contact_groups
      assign where service.vars.contact_groups
    }

**Comment by chas0rde** [comment]
Would also love that.
We configure Responsible, Deputy and "others to inform" (array) via Director on hosts and services.
It would be great to be able to have less (rather than per-user) notification objects in director in this way.

E.g. something like "notify-host-mail" with Users "$host.vars.responsible$" and assign where $host.vars.responsible != "" would be nice.

This way we could reduce the number of notification objects in director to 6 per media instead of 2 per media per user (which totals with e.g. 50 users to 6 instead of 100 notifications per media)
"media" being e.g. mail, sms, telegram...

**Comment by Thomas-Gelf** [comment]
This is now going to happen :tada:

**Comment by Thomas-Gelf** [comment]
### Notification Configuration

![grafik](https://user-images.githubusercontent.com/553008/205028392-c72e31bf-2bcf-4357-a51f-2a25148ceb6f.png)

### Rendered Icinga Configuration

![grafik](https://user-images.githubusercontent.com/553008/205028987-d011d2dd-c874-4a1b-9046-35b65da79f12.png)
