### ISSUE TITLE
[dev.icinga.com #12947] Service assignment based on ssh command output 

### ISSUE THREAD

**Issue by icinga-migration** [Icinga/icingaweb2-module-director#502]
This issue has been migrated from Redmine: https://dev.icinga.com/issues/12947

**Created by swizzly on 2016-10-19 14:41:51 +00:00**

Assignee: _(none)_
Status: _New_ 
Target Version: _(none)_
Last Update: _2016-10-20 07:14:38 +00:00 (in Redmine)_

---

Hi,

I am wondering whether is it possible in Director, to assign a service to a host based on the result of a remotely (SSH) executed command on the host?
In detail: There are several hosts with some special attributes, that are nowhere centrally registered (no LDAP/PuppetDB whatsoever). In order to find out whether the attribute is defined, a command need to be executed on the host. If the query is successful, then it means the attribute is set on the given host, and accordingly a service should be activated on the given host.
The attributes are relatively static, it means it changes maybe 1-2x in a year. I could manually assign the service to the hosts, but it is not so elegant, and it can be forgotten.

cheers
Zoltan

**Comment by Thomas-Gelf** [comment]
Closing this one, as we solved it with a custom `PropertyModifier` running a custom script every time a script-generated lookup file is outdated. The modifier is configurable, but still quite opinionated. It could IMO be made more generic with little effort, that's why I leave this screenshot here before closing the issue:

![property-modifier_orapoollist](https://user-images.githubusercontent.com/553008/27457159-f5d5a9f6-57a3-11e7-90e1-8d867fc6974f.png)
