### ISSUE TITLE
allow command_endpoint to be configured for service templates #229

### ISSUE THREAD

**Issue by cbnorman** [Icinga/icingaweb2-module-director#745]
i need to be able to specify command_endpoint for services either directly or by referencing a host.vars. currently i can set services to use "run on agent" which adds  "command_endpoint = host_name" to the config. the problem with that is when the host_name is not an agent but i don't want the service executed on the master. icinga2 docs suggest configuring a vars.client_endpoint = endpoint on the host and then every service for that hosts is configured with command_endpoint = host.vars.client_endpoint.

i have linked a similar request which looks like it added this for host templates only.

**Comment by cbnorman** [comment]
is there any work around for this?

**Comment by mbassett** [comment]
Your question is a bit confusing.   'Run on Agent'  means it expects the service to be attached to a machine running Icinga Agent.  If you are applying checks with run on agent set to machines that do not have icinga agent installed you're going to have problems.

If a check does not have 'Run on Agent' checked it will be executed from the icinga master/satellite box depending on your setup.  

The name you use for the host name is what icinga will use when it attempts an API call to the agent, and if your agent is not configured with that same name you will also fail.

For me, I import nodes from EC2, so all my host names are instance ID's  i-23234234 , the readable name is set in display_name.   Icinga recommends you add agents with the fqdn of the instance, but since my hosts are in by instance id's i have to register my agents as their instance-id not their fqdn.  

So in essence, your particular configuration is paramount to determining what the solution is.  There are many ways to accomplish the same tasks.

**Comment by cbnorman** [comment]
i think i didnt wait long enough after configuring the hosts to be on a satellite zone, once i did the services for that host would also run from that satellite host instead of the master. this suits my requirements so this issue can be closed. 
thanks for looking into this, appreciated! please close this issue

**Comment by mzhaase** [comment]
This is not closed. Yes you can set a host to use a specific command endpoint, but you cannot do it for a service. For example for a webserver it is common to monitor served websites both internally and externally, so you would like to have a service monitoring the website from an external location. Currently you have to create a seperate host for that. If you monitor a website from multiple locations you end up with three or four times the amount of hosts, when in reality it should be a service instead.

**Comment by fmuell** [comment]
Its possible, but strongly depends on your setup (not the director settings). If you only define satelite zones in the /etc/icinga2/zones.d/ folder all services are scheduled by the satelite systems. For remote checks you define your service http as usual with no specific "command_endpoint" property. The satelites will perform this http check remotely.

For local checks you define another service with same apply rules, but here you set:
command_endpoint = host.name (if your webservers icinga endpoint name matches the hostname) otherwise you have to take another custom var on your webservice like:

vars.icinga_endpoint = "webservers-endpointname"

in the service all you have to do is:
command_endpoint = host.vars.icinga_endpoint

This service will be performed locally on the webserver.

By this way you dont need to set a service endpoint in the director at all.
