### ISSUE TITLE
Automatic conversion for a varible starting with a number to dictionary does not work

### ISSUE THREAD

**Issue by SimonHoenscheid** [Icinga/icingaweb2-module-director#792]
[Code](https://github.com/Icinga/icingaweb2-module-director/blob/83b5b27803420e986177562569b0dd6fa130e0ab/library/Director/IcingaConfig/IcingaConfigHelper.php#L108)

```
information/cli: Icinga application loader (version: v2.6.0)
information/cli: Loading configuration file(s).
critical/config: Error: syntax error, unexpected T_NUMBER, expecting T_IDENTIFIER
Location: in [stage]/zones.d/director-global/service_apply.conf: 40:10-40:10
[stage]/zones.d/director-global/service_apply.conf(38): 
[stage]/zones.d/director-global/service_apply.conf(39):     assign where match("b3par*", host.name) && match("btsu3par*", host.name)
[stage]/zones.d/director-global/service_apply.conf(40):     vars.3par_commad = "check_pd"
                                                                 ^
[stage]/zones.d/director-global/service_apply.conf(41): 
[stage]/zones.d/director-global/service_apply.conf(42):     import DirectorOverrideTemplate
```

**Comment by lazyfrosch** [comment]
I think the problem is here:
https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/CustomVariable/CustomVariables.php#L303

CustomVariables should be rendered like a Dictionary.

The renderKeyName here uses a different RegExp...
https://github.com/Icinga/icingaweb2-module-director/blob/master/library/Director/CustomVariable/CustomVariables.php#L362

**Comment by Thomas-Gelf** [comment]
You're right, thanks!
