### ISSUE TITLE
Change argument order of icingacli-businessprocess

### ISSUE THREAD

**Issue by cstegm** [Icinga/icingaweb2-module-director#795]
When you use icingacli-businessprocess and activate --details the order of arguments is not correct:

--details active Inspect Snippet: 
   ```
   command: [
        "/usr/bin/icingacli",
        "businessprocess",
        "check",
        "process",
        "--config",
        "Example",
        "--details",
        "Global"
      ],
```
Plugin Output:
```
ERROR: Exception in /usr/share/icingaweb2/modules/businessprocess/library/Businessprocess/BpConfig.php:504 with message: The node "" doesn't exist`
```
it should work with the following order:
   ```
   command: [
        "/usr/bin/icingacli",
        "businessprocess",
        "check",
        "process",
        "--details",
        "--config",
        "Example",
        "Global"
      ],
```

**Comment by Thomas-Gelf** [comment]
This should have been fixed in recent ITL in the Icinga 2 repository. Please eventually re-run the Director Kickstart to see the current version in the GUI, but even if you don't - it should just work. In case it doesn't please file another bug request against the [Icinga 2 issue tracker](https://github.com/Icinga/icinga2), that's where ITL commands are handled.

Cheers,
Thomas
