### ISSUE TITLE
Rename of Datafield not automatically applied to Hosts

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-director#818]

**Comment by l13t** [comment]
It also keeps in database records with old datafield names.

**Comment by widhalmt** [comment]
When renaming a custom field, the old versions stays in the configuration. The only workaround I could find was readding a field with the old name, set a value, save, set it to an empty value and remove the field then save again.

**Comment by Thomas-Gelf** [comment]
@widhalmt: you can go to Datafields and delete it there, it will ask you whether it should also wipe related custom vars. In case you renamed the field, just create a new one and delete it. It will ask whether it should remove all related vars from services, hosts, commands...

**Comment by widhalmt** [comment]
@Thomas-Gelf thank you! Shame on me. I used this wiping today but didn't think of it as a solution to previously renamed fields. We just created a new field with the old name, deleted it and wiped all occurances of the old field. Works like a charm.

But the renaming didn't work nevertheless. In short: Thanks for the workaround but this issue is still a thing.   And thanks for your ultra-fast reply.

**Comment by Thomas-Gelf** [comment]
> Thanks for the workaround but this issue is still a thing

That's why it hasn't been closed yet ;-)

> And thanks for your ultra-fast reply

You're welcome!

**Comment by Thomas-Gelf** [comment]
Had a need for this right now, so I implemented it right away. Will be part of 1.4.0, no plans to backport it to 1.3.2 - sorry.
