### ISSUE TITLE
[Suggestion]Quick way to allow a lot of currently unsupported datafield features.

### ISSUE THREAD

**Issue by spali** [Icinga/icingaweb2-module-director#845]
currently I miss painfully some DataField features in director which I don't know how to solve:
- Integer DataField can't be filled with variable macro (i.e. in service apply-rule cant use $host.vars.myinteger$, this fails because of the integer validation.
- can't use Dictionaries
- can't use += for adding to inherited values.

I think at least for the last two, there exists already some issues, and for Dictionaries, I have seen the in progress pull request.

My idea is implement DataField of type "expression". Which will not be escaped nor in any way special parsed. But the user has to define the "whole" line of the configuration including the variable name.
This would allow to define
- `vars.myArray += [$myAdditionalValue$]`
- `vars.myInteger = $host.vars.myinteger$`
- `vars.myhash = { }`

and probably would solve some additional and future requirements as long as it is not native supported by director.

I'm not a php dev, but I think the effort would be small for the weight of improvement. I know, this could probably be dangerous, because it could break a lot, but it allows to use director as much as possible without going back to manually defining such requirements in the config files.
Maybe this can be globally disabled and enabled to prevent using it if not really required.
In my naiv mind, I would treat it like a string DataField everywhere except during rendering, just paste the whole variable value (not name) in the config.

Would this probably work?

**Comment by Thomas-Gelf** [comment]
Hi @spali,

you know, shortcuts are the longest path between two given points ;-) You can currently perfectly define Icinga DSL in your command arguments, that should allow you to solve quite some weird requirements. Have a look at #496 for a related example.

`vars.something = host.vars.something` should not be required at all, as all your host variables should already be available in all it's services unless the service overrides that var. And as you mentioned, there should already be related issues for the rest of your wish-list.

Sure, a blob allowing for "plain Icinga Config" would make it easier to get some things solved. That would occur at the price of the Director losing the possibility of being able to fully resolve your configuration. That is an essential requirement for a bunch of current and future features, so this would be a price I'm not willing to pay. This might be possible once we sharpened some other features and got a better understanding of the side-effects that are to be expected once a user uses such a feature.

**Comment by spali** [comment]
My problem is I need the DSL (or at least a dictionary) in host and service and also in their template counterparts. Currently building up a new setup of icinga and would really like to keep my fields hierarchical and not only flat from the beginning). Hope the PR will get soon done :)

regarding the host.vars in services.... I use it in service templates, this is probalby the reason I don't have it there automatically... but It works that way I use it. I know in the Service itself (or apply-rule) there it works automatically.

Probably if I find some time, I will look into this blob thing :) You know better the potential negativ impact, but for me it looks like in the worst case I have a lot of string which I need to migrate by hand some time in the future. I don't think I can make something completely broken.
I let you know if I will get some results on this.

**Comment by Thomas-Gelf** [comment]
You can use the Director CLI, API or Sync rules to fill custom variables with a dictionary if that helps - that's perfectly legal. It's not in the GUI yet, because of Dictionary -> nested Data types -> form validation -> cool, but requires quite some love. The pending feature request offers a blob with JSON support as a workaround, but that's something I can hardly offer as the default official way.

Related to the services -> Director doesn't show the host variable in the template (for obvious reasons, it isn't there yet), but it should still automagically be available in your command at execution time. The other way round (overriding defaults defined in a service template or apply rule on a single host) is pretty tricky with plain Icinga config, but should be trivial with Directors service var override feature.

You could also show me some more specific use cases you're trying to solve, eventually I (or someone else) could show up with a slightly different approach solving the same task.

Anyways, any help with the features mentioned above is of course absolutely appreciated!

**Comment by spali** [comment]
> You can use the Director CLI, API or Sync rules to fill custom variables with a dictionary if that helps

didn't realized this way is possible, thanks, but I think this would make it more complicated for my need.

> You could also show me some more specific use cases you're trying to solve, eventually I (or someone else) could show up with a slightly different approach solving the same task.

probably you read the forum post in the monitoring forum from someone else (for snmp_load to put all options in a dictionary)...  I try to accomplish the same task:
I just want a dictionary per service on the host or host template to override selectively options required by the service. I then in the service object I want to reference the dictionary and split it up for the specific argument variables by referencing the dictionary elements. It's just to prevent to much variables on objects. In the future also with apply-for if multiple services should be created.
As of today I have to define a datafield and the corresponding fields for each single argument that I want to selectively override.

I can try to get some time to help. I already sneaked a peek to the code and db to see the potential effort for a quick solution. Currently there seems to be a mix of the handling of the different types with json and other formats.
Probalby a suggestion from my side... why not use the serialize functionality of PHP to save all objects. this would preserve the type without the need for parsing and special handling. Theoretically you could save a complete object containing the data and probably some metadata to differentiate between types you need to store in the same PHP type but want to handle differently in the code. Then the handling would be a lot easier I think.
Probably the answer is what you already wrote to me initially? ;-)

> you know, shortcuts are the longest path between two given points ;-)

**Comment by Thomas-Gelf** [comment]
> probably you read the forum post in the monitoring forum

No, I didn't for quite some time, been pretty busy. Therefore sorry, no idea what problem you're talking about.

> As of today I have to define a datafield and the corresponding fields for each single argument that I want to selectively override.

Wondering how you would otherwise manage it to fill in such values when you are neither using CLI/API/Sync nor specifying related fields?! JSON-blob for everything? Then VIM might be your preferred configuration GUI ;-)

Fields are subject to inheritance and also fields assigned to commands can be used at a service level. And I'm not aware of many commands that could benefit from structured data. And when it goes to host-based dictionaries generating services with apply rules - I'm not a big fan of them at all. They might help with manual configuration, but from my point of view using the same workflow in the Director would just add one more useless layer of abstraction. Technically there isn't much difference between apply for based on a hash defined on a host - and single service added to that host. Both of them are redundant in the very same way, with the single service offering the advantage of still being able to benefit from multi-inheritance.

> why not use the serialize functionality of PHP to save all objects

Bad idea. First of all, we use JSON where it goes to serialize objects. PHPs own serialization implementation (like the same toys in every language) would open huge attack vectors. And useless, as the database can no longer work with the data. Think of permissions and restrictions, environments with tens (or hundreds) of thousands of monitored objects. The Director schema already got some enhancements storing resolved and "flat" vars, to speed up many features. See `icinga_var`, `icinga_flat_var` and related assignment tables. In future we'll persist all properties as JSON, resolved "flat" vars in addition to that, all of those for single objects (being subject to inheritance) and fully resolved.

But that work has been frozen and Director development has been slowed down. Main reason is that we are currently working hard on a new alternative data backend for Icinga 2, which should succeed the IDO. Quite some ideas that started in the Director are going to be finalized in that project. Therefore, some tasks are overlapping with what the Director does. So it makes no sense for us to develop similar functionality twice.

Just to give you an idea, we want to be able to "show only hosts with '/data' in the vars.some.disks dictionary" in a fraction of a second, even when monitoring 100k hosts. No chance to fetch all of them into userspace to deserialize a proprietary data construct for every single click. Currently there is no way to do this in Icinga Web 2 with the IDO, Director could already answer such query in half a minute, given that it currently would be forced to resolve all involved inheritance in memory. This has to be more like 50-100ms.

That project currently has highest priority for us. No chance to get merged a feature with the potential to hinder that goal, sorry. So if your plans point in that direction - chances are VERY high that related pull requests are going to be rejected. You have been warned ;-) Still, there is nothing wrong with storing Dictionaries as JSON to the DB, that's what the Director already does. You could extend your local installation with some hacky form field that behaves that way, try to steal some code from the related pull request.

Sooner or later there will be official Dictionary support. We'll not allow to store Icinga DSL "directly" to a custom variable, but we'll introduce the possibility to roll out custom functions and to use them with special dedicated data types. That way we'll be able to offer more DSL support in a controlled way. You do not want to offer someone with limited access to Director to write DSL, as that would allow him to take over your whole Icinga installation.

I'll close this issue for now, as related ones should exist for every single task - if not please create the missing ones in a more specific way. This one targets too many different things. And my offer still stands: show me a specific task you're trying to solve (nothing abstract, name it, give examples), I could eventually show you an alternative way to achieve your goal in the meantime.

Cheers,
Thomas

**Comment by spali** [comment]
Hi Thomas

Thanks for your detailed answer. This helps me a lot, because I already thought about to invest some time to develop a clean solution support my ideas with the consequence to implement a lot new code for the backend of Director. But you pointed exactly on the problem I thought about and it wouldn't be worth to put such a lot effort in it, especially because I never worked with the frameworks in use and I had to start from the beginning to learn the current design of Director.
But in this case, I absolutely agree with you and hope the effort you guys put into Icinga will lead to a much more stable and future proof solution.

cheers
Thomas

**Comment by Thomas-Gelf** [comment]
Hi Thomas :laughing:

You could eventually also evaluate putting your code in a [custom module](https://github.com/Icinga/icingaweb2-module-training/blob/master/doc/icinga-web-2-erweitern.md), that's upgrade-safe, provide a custom ImportSource for the Director (there's a hook for them) and ship your special data. You could look at the [fileshipper module](https://github.com/Icinga/icingaweb2-module-fileshipper) for a related example.
